### ISSUE TITLE
Problem during the installation 

### ISSUE THREAD

**Issue by fitibirli** [theangryangel/logstash-output-jdbc#103]
- Logstash Version: 5.5.2
- Operating System: W7

Hello, i have a problem trying to install the plugin:

Im running:
bin/logstash-plugin install logstash-output-jdbc

And the output is:

Validating logstash-output-jdbc
Installing logstash-output-jdbc
Error Bundler::HTTPError, retrying 1/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 2/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 3/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 4/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 5/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 6/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 7/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 8/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 9/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Error Bundler::HTTPError, retrying 10/10
Network error while fetching https://rubygems.org/quick/Marshal.4.8/logstash-dev
utils-1.3.3-java.gemspec.rz
Too many retries, aborting, caused by Bundler::HTTPError
ERROR: Installation Aborted, message: Network error while fetching https://rubyg
ems.org/quick/Marshal.4.8/logstash-devutils-1.3.3-java.gemspec.rz

Im missing something?

Thanks

**Comment by theangryangel** [comment]
This indicates you've had some kind of issue communicating with rubygems.org, which is where the `logstash-plugin` command installs plugins from. This isn't connected at all with the plugin and isn't something I can really help with. I'd suggest retrying, as it may have been an intermittant issue at their end. If you have some kind of proxy you'll need to have that configured appropriately.

If you have no internet access you'll need to download the gem manually from https://rubygems.org/gems/logstash-output-jdbc/versions/5.3.0-java and then run `logstash-plugin install path/to/gem`.
