### ISSUE TITLE
Getting Duplicate Records while inserting Data into Database

### ISSUE THREAD

**Issue by rkhapre** [theangryangel/logstash-output-jdbc#108]
Hi
I am using Oracle DB as my output, i am using insert query to post the data into table.
It is working work, but the problem is since my pipeline is ON and keep running for a longer period of time, it is inserting duplicate records.

How can i make sure if the record is once read then come out from pipeline or do not insert duplicate records.

Do we have any Document Key like elastic (_id) or like sincedb path.

In my current dataset there is no field which i can make as primary key in table. 
So i need a way, if it read once then do not insert again.

Regards
Ritesh

**Comment by theangryangel** [comment]
The plugin makes no assumptions about the shape of your data. I will say if you're reading the data multiple times and getting duplicates then you shouldnt really be surprised you're getting duplicates in your output.. your input may need tweaking.

That said, in the past I've used the `fingerprint` filter and setup the jdbc output statement to either do an `upsert` or a `if not exists insert...`, depending on the database engine, using the fingerprint as a way to uniquely identify your data.
