### ISSUE TITLE
With csv input first records is missed, this is not the case with elastic

### ISSUE THREAD

**Issue by rkhapre** [theangryangel/logstash-output-jdbc#112]
Hi

In a csv file i have 300 records, when i insert in database of Oracle, it gives me 299 records only.
The first records is missed every time.
I am using file input plugin

With exact same configuration when i post to elastic, it works perfectly ( 300 records)

Note : 
1. In my csv file i have new line in the last line
2. I clear sincedb path before i run it.
3. It works perfectly with elastic as output

Regards,Ritesh

**Comment by theangryangel** [comment]
The output plugin processes whatever it’s given by input/filters. It has no filtering/skipping mechanism built into it. The only reason it would fail on a row is if your statement fails. But if this did happen it would output a log entry saying why. This is not a bug with the output plugin.

**Comment by rkhapre** [comment]
Okay i got it. let me debug more
