### ISSUE TITLE
How do i use statement for 2 sql queries : Truncate and insert

### ISSUE THREAD

**Issue by rkhapre** [theangryangel/logstash-output-jdbc#113]
Hi
I am using statement to insert data, before inserting the data i want to first truncate and then insert it.
How can i truncate and insert within a single statement=>

Regards
Ritesh

**Comment by rkhapre** [comment]
Hi All

I tried two statements like this below, but still not work
statement =>
statement ->

Anyone has any idea, how should i make it work?

Thanks!

**Comment by theangryangel** [comment]
Most JDBC drivers only allow 1 statement per-call. I believe the exception is MySQL which has a `allowMultiQueries` option, which you can set to true.

if you need to run multiple statements the only other way I can suggest doing it at this time is with a stored procedure. Take a look at https://github.com/theangryangel/logstash-output-jdbc/issues/90

**Comment by rkhapre** [comment]
Thanks You, will try this.
