### ISSUE TITLE
Logstash 6.x

### ISSUE THREAD

**Issue by bitva77** [theangryangel/logstash-output-jdbc#118]
Hi!  Just wondering if this has been tested with Logstash 6.x?

That's all  :)

Thanks!

-Matt

**Comment by theangryangel** [comment]
I'm not yet using the plugin against v6 in my own environment, but I am aware others are without issue (see https://github.com/theangryangel/logstash-output-jdbc/issues/91). The plugin API between v5 and v6 is compatible.
