### ISSUE TITLE
logstash mysql username contains '%' then got an error

### ISSUE THREAD

**Issue by wdyun** [theangryangel/logstash-output-jdbc#119]
Pipeline aborted due to error {:pipeline_id=>"main", :exception=>java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "en", :backtrace=>["java.net.URLDecoder.decode(java/net/URLDecoder.java:194)", "com.mysql.jdbc.NonRegisteringDriver.parseURL(com/mysql/jdbc/NonRegisteringDriver.java:651)", "com.mysql.jdbc.NonRegisteringDriver.acceptsURL(com/mysql/jdbc/NonRegisteringDriver.java:266)", "com.zaxxer.hikari.util.DriverDataSource.<init>(com/zaxxer/hikari/util/DriverDataSource.java:105)", "com.zaxxer.hikari.pool.PoolBase.initializeDataSource(com/zaxxer/hikari/pool/PoolBase.java:342)", "com.zaxxer.hikari.pool.PoolBase.<init>(com/zaxxer/hikari/pool/PoolBase.java:117)", "com.zaxxer.hikari.pool.HikariPool.<init>(com/zaxxer/hikari/pool/HikariPool.java:109)", "com.zaxxer.hikari.HikariDataSource.getConnection(com/zaxxer/hikari/HikariDataSource.java:97)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:438)"

**Comment by wdyun** [comment]
https://stackoverflow.com/questions/6067673/urldecoder-illegal-hex-characters-in-escape-pattern-for-input-string/18368345
user '%25' to replace '%'

**Comment by theangryangel** [comment]
MySQL's JDBC driver uses URLDecoder, despite JDBC strings not being URL strings. 

If you have characters that the jdbc string parser in your driver cant handle properly, you can use the username and password configuration options instead.

i.e.
```
jdbc {
        driver_class => "com.mysql.jdbc.Driver"
	connection_string => "jdbc:mysql://HOSTNAME/DATABASE"
	username => "use%r"
	password => "asdasd%^^^??"
	statement => [ ... ]
	}
```
