### ISSUE TITLE
UPDATE Statement Help

### ISSUE THREAD

**Issue by karnamonkster** [theangryangel/logstash-output-jdbc#124]
##  Environment
* Version of plugin used: 5.1.0
* Version of Logstash used:  5.6.4
* Database engine & version you're connecting to: MySQL ver 14.14 Dist 5.5.54
* Have you checked you've met the Logstash requirements for Java versions?: OpenJDK 1.8.0_151

I need help with the UPDATE Statement to be passed in the query. Can you please suggest some examples.
My input is from Elasticsearch which fetches around 30 fields for which i need to update the database.
MySQL database structure is created

**Comment by theangryangel** [comment]
It's standard SQL... If you're having difficulty I'd suggest researching or employing someone who can assist further. I dont have the time or will to each basic SQL beyond this. There are plenty of tutorials and documentation around to help.

The below example assumes you have something generating events with fields named `field1`, `field2`, and `id`. It also assumes id matches with an existing row in the table.

```
jdbc {
  driver_class => "com.mysql.jdbc.Driver"
  connection_string => "jdbc:mysql://HOSTNAME/DATABASE?user=USER&password=PASSWORD"
  statement => [ "UPDATE yourtablename SET field1 = ?, field2 = ? where id = ?", "field1", "field2", "id" ]
	}
```
