### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: relation "my_table_name" does not exist

### ISSUE THREAD

**Issue by shoaibjdev** [theangryangel/logstash-output-jdbc#126]
logstash-6.2.2
Postgre JDBC Jar: postgresql-42.1.4.jre7.jar

Have created the table and able to connect from other JDBC applications. But for logstash-output-jdbc getting this error

org.postgresql.util.PSQLException: ERROR: relation "my_table_name" does not exist

**Comment by theangryangel** [comment]
The error is from PostgreSQL and tells you the table doesn’t exist. 

Either you’ve configured the plugin with the wrong details (I.e an account that doesn’t have access, etc) or you’ve typoed the table. This isn’t an issue with the plugin itself a.m. is entirely down to your environment/setup. It is virtually impossible for me to help further.
