### ISSUE TITLE
java.lang.IllegalAccessError: tried to access class org.postgresql.Driver$ConnectThread from class org.postgresql.Driver

### ISSUE THREAD

**Issue by Uvizor** [theangryangel/logstash-output-jdbc#127]
Hi there! I updated my ELK from version 6.2.3 to 6.3.0 and in 6.3.0 logstash-output-jdbc can't starts.
In logsthash-plain. log i have next errors:

```
[2018-06-21T17:16:00,948][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2018-06-21T17:16:01,047][ERROR][org.logstash.Logstash    ] java.lang.IllegalAccessError: tried to access class org.postgresql.Driver$ConnectThread from class org.postgresql.Driver

```

**Comment by theangryangel** [comment]
I am out of the country and without any computer/laptop until next week. If this is urgent I suggest rolling back, and I will see if I can reproduce this when I’m back at home. I have not yet tested with 6.3.0. Can you tell me what version of the Postgres driver you’re using and what version of Java?

**Comment by Uvizor** [comment]
Here my plugin's config.
```
jdbc {
    driver_jar_path => "/opt/cluster/logstash/lib/postgresql-42.2.1.jar"
    driver_class => "org.postgresql.Driver"
    connection_string => "jdbc:postgresql://example.com/elk_db"
    username => "username"
    password => "password"
    statement => [ "CREATE TABLE IF NOT EXISTS table_name (field1 text UNIQUE, field2 text);
                                    INSERT INTO table_name (field1, field2)
                                            VALUES (?, ?)
                                            ON CONFLICT (field1) DO UPDATE
                                            SET field2 = excluded.field2;"
                            , "%{source}", "%{@timestamp}"]
}
```
Also I create topic on logstash forum https://discuss.elastic.co/t/output-jdbc-plugin-crash-on-6-3-0/136912, and opened issue on github https://github.com/elastic/logstash/issues/9775
Thanks for answer!
P.S. Very helpfull plugin, thank you for your work!

**Comment by theangryangel** [comment]
Please don’t open tickets for this plugin against logstash core. Although the upgrade may or may not be the cause it’s not relevant to that project and will probably just get closed by elastic.

**Comment by Uvizor** [comment]
Ok. I've closed issue against logstash core.

**Comment by Uvizor** [comment]
Hi. Have you tested plugin on 6.3.0 already?

**Comment by theangryangel** [comment]
Not yet. When I have time I will :)

**Comment by trosene** [comment]
@Uvizor Have you tried placing your jar file in the logstash-core\lib\jars directory? I was experiencing this same error even when declaring the jar path. After placing it in the logstash-core lib I am back up and running.

**Comment by Uvizor** [comment]
@trosene When i put jar file in logstash-core\lib\jars and declare path (driver_jar_path => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.2.2.jar"), plugin works again. Thank you!
