### ISSUE TITLE
plugins in logstash 6.3.2 can not start,some error message

### ISSUE THREAD

**Issue by CodingOX** [theangryangel/logstash-output-jdbc#130]
when i star, error message:
`[2018-08-21T16:02:21,693][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<TypeError: could not coerce Fixnum to class java.lang.String>, :backtrace=>
["/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-jdbc-5.3.0-java/lib/logstash/outputs/jdbc.rb:154:in `setup_and_test_pool!'", 
"/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-jdbc-5.3.0-java/lib/logstash/outputs/jdbc.rb:127:in `register'",
 "org/logstash/config/ir/compiler/OutputStrategyExt.java:97:in `register'",
  "org/logstash/config/ir/compiler/OutputDelegatorExt.java:93:in `register'", 
  "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:340:in `register_plugin'",
   "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:351:in `block in register_plugins'", 
   "org/jruby/RubyArray.java:1734:in `each'", 
   "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:351:in `register_plugins'", 
   "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:728:in `maybe_setup_out_plugins'", 
   "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:361:in `start_workers'", "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:288:in `run'", 
   "/Users/liuchunfu/develop/elk/bin/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:248:in `block in start'"], :thread=>"#<Thread:0x5a943232 run>"}
[2018-08-21T16:02:21,721][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}`

what can i do ?

**Comment by theangryangel** [comment]
Can you paste a copy of your config please? Specifically the jdbc output part. 

Please note I’ve not yet had time to test the plugin with 6.3 and I do not know if there are compatibility issues yet.

**Comment by CodingOX** [comment]
@theangryangel Thanks，
The reason for this mistake is my configuration file is wrong. After my tests, everything worked well.
