### ISSUE TITLE
ES Input to Postgresql Output - Error with numeric values

### ISSUE THREAD

**Issue by nathanemmisoncdl** [theangryangel/logstash-output-jdbc#133]
## Expected & Actual Behavior

I am using Logstash to use Elasticsearch 6.0 as an Input and I want to Output that to Postgresql using this JDBC conector. I have a table with mixed text and numeric fields.

Text fields in ES seem to work okay but if the field in ES is a number value, it then can not Output to the database.

I first got this error: 

`"fieldname" is of type numeric but expression is of type character varying`

I decided to recreate my table using all text values but then when it passes that error, all of the values for the columns are null.

## Your Environment

* Version of plugin used: v2
* Version of Logstash used: Attempted on both 6.4.0 and 6.2.3
* Database engine & version you're connecting to: Postgresql 10.4
* Have you checked you've met the Logstash requirements for Java versions?: Yes

**Comment by theangryangel** [comment]
Can you provide some sample data please? There are tests which cover this scenario, so it should be working.

**Comment by nathanemmisoncdl** [comment]
Agh, apologies. I didn't realise the fields are case sensitive and it is now working.
