### ISSUE TITLE
Unable to install the plugin offline in logstash-6.4.0. Even prepare-offline-pack is throwing a run time error.

### ISSUE THREAD

**Issue by shravan521** [theangryangel/logstash-output-jdbc#134]
Unable to install the plugin offline in logstash-6.4.0. 
## Expected & Actual Behavior
When installing the plugin offline it is trying to connect rubygems.org and failing to install.

bin/logstash-plugin install logstash-output-jdbc-5.3.0-java.gem
Error is below:
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/

Even prepare-offline-pack is throwing a run time error.
bin/logstash-plugin prepare-offline-pack logstash-output-jdbc
Error is below:

RuntimeError: Response not handled: Net::HTTPForbidden, path: /downloads/logstash-output-jdbc-5.3.0.gem
          download_file at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/paquet-0.2.1/lib/paquet/utils.rb:30
           download_gem at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/paquet-0.2.1/lib/paquet/gem.rb:106
  block in package_gems at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/paquet-0.2.1/lib/paquet/gem.rb:48
                   each at org/jruby/RubyArray.java:1734
           package_gems at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/paquet-0.2.1/lib/paquet/gem.rb:42
                   pack at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/paquet-0.2.1/lib/paquet/gem.rb:33
                execute at /home/oracle/Logstash/logstash-6.4.0/lib/pluginmanager/offline_plugin_packager.rb:88
                package at /home/oracle/Logstash/logstash-6.4.0/lib/pluginmanager/offline_plugin_packager.rb:115
                execute at /home/oracle/Logstash/logstash-6.4.0/lib/pluginmanager/prepare_offline_pack.rb:41
                    run at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
                execute at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                    run at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
                    run at /home/oracle/Logstash/logstash-6.4.0/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
                 <main> at /home/oracle/Logstash/logstash-6.4.0/lib/pluginmanager/main.rb:48

## Your Environment

* Version of plugin used:  logstash-output-jdbc-5.3.0
* Version of Logstash used:  logstash-6.4.0
* Database engine & version you're connecting to: oracle 11g XE 
* Have you checked you've met the Logstash requirements for Java versions?: yes java1.8

**Comment by shravan521** [comment]
I know its too early ask but please let me know if there is a quick around to this..

**Comment by theangryangel** [comment]
Install it on a PC with network access and copy it. I assume the latest release doesnt have vendor'ed jars and is trying to reach out to the internet to get them.

**Comment by shravan521** [comment]
Thank you for the quick response. So should I copy any particular folder or Logstash folder itself?

**Comment by theangryangel** [comment]
5.4.0 has been pushed to rubygems with the jars bundled.

FWIW the directory to copy would be the `logstash-output-jdbc` which lives inside the logstash installation directory (depends where you put it, but usually `vendor/bundle/jruby/<version>/gems`)
