### ISSUE TITLE
Error with inserting too many parameters

### ISSUE THREAD

**Issue by seanziee** [theangryangel/logstash-output-jdbc#139]
I'm using logstash 6.1.2 and I'm getting the following error: Any advice on how I can insert more than 45 values into my sql table? I'm inserting about 58 colunms

`{:exception=>java.sql.SQLException: Parameter index out of range (46 > number of parameters, which is 45).}`

`statement => [ "INSERT INTO production VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ,?, ?, ?, ?, ?, ?, ?, ? ,?, ?, ?, ?, ?,?, ?, ?, ?, ?, ?, ? ,?, ?, ?, ?, ?, ?, ?)", "[id],[location], .......`

**Comment by theangryangel** [comment]
Usually you get that there when you have a mismatched number of placeholders (`?`) and parameters. Double check you've not made a mistake.

**Comment by seanziee** [comment]
Ok, I checked and you were right! Thanks!! :D
