### ISSUE TITLE
how to insert json object in statement?

### ISSUE THREAD

**Issue by jiekechoo** [theangryangel/logstash-output-jdbc#14]
"geoip": {
      "ip": "120.27.47.144",
      "city_name": "Beijing"
}

how to insert 'ip' or 'city_name' in statement?

**Comment by theangryangel** [comment]
I believe something like this should work for you:

`statement => [ "INSERT INTO log (ip, city_name) VALUES(?, ?, ?)", "[geoip][ip]", "[geoip][ip]" ]`

**Comment by jiekechoo** [comment]
got it, thanks
