### ISSUE TITLE
IllegalAccessError CompoundCacheKey

### ISSUE THREAD

**Issue by nasrinmansour** [theangryangel/logstash-output-jdbc#140]
Hi, could you help me , what is this error ? how can i solved it
on logstash 5.6
[ERROR][logstash.inputs.jdbc     ] Unable to connect to database. Tried 1 times {:error_message=>"Java::JavaLang::IllegalAccessError: com/mysql/jdbc/ConnectionImpl$CompoundCacheKey"}

**Comment by theangryangel** [comment]
* What MySQL jar are you using?
* What MySQL version are you connecting to?
* What Java version are you on?

**Comment by theangryangel** [comment]
If I remember correctly logstash 5 *requires* a different version of java. So you should've updated java and changed your MySQL jar.. If you didn't do that it may explain your issue.

I know MySQL works because it's included as part of the test suite.
