### ISSUE TITLE
Insert emoji into mysql(utf8mb4) varchar field fail(Incorrect string value SQLException)

### ISSUE THREAD

**Issue by silbertmonaphia** [theangryangel/logstash-output-jdbc#141]
## Expected & Actual Behavior

Insert content "都没有啊😭，神兵也没有" using logstash-output-jdbc, but get an error below:

`Exception:java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\xAD\xEF\xBC...' for column 'content' at row 1`

if I insert the content via mysql client, that works.

## Environment
* Version of plugin used:  
./logstash-plugin list --verbose | grep logstash-output-jdbc  
5.3.0  

* Version of Logstash used:  
./logstash --version  
5.5.3  

* Database engine & version you're connecting to:  

    ```sql
    SHOW version()  
    5.6.16-log  
    ```

    ```sql
    SHOW VARIABLES LIKE 'character%'

    character_set_client       utf8mb4
    character_set_connection   utf8mb4
    character_set_database     utf8mb4
    character_set_filesystem   binary
    character_set_results      utf8mb4
    character_set_server       utf8mb4
    character_set_system       utf8
    ```
 
    ```sql  
    Table Schema: 

    CREATE TABLE `question_log` (
      `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
      `content` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '问题内容',
      PRIMARY KEY (`id`),
      KEY `content` (`content`(191)) USING BTREE,
    ) ENGINE=InnoDB AUTO_INCREMENT=609 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    ```

* Have you checked you've met the Logstash requirements for Java versions?:  
```shell
java -version
java version "1.8.0_112"  
```

**Comment by theangryangel** [comment]
Try adding `?useUnicode=yes&characterEncoding=UTF-8` to your connection string

**Comment by silbertmonaphia** [comment]
I've tried it just now, but still got the error  
here is my logstash output config:  
```ruby
 jdbc {
	connection_string => "jdbc:mysql://10.10.00.00:3306/admin?user=xxxx&password=xxxx&useUnicode=yes&characterEncoding=UTF-8"
	unsafe_statement => true
	max_pool_size => 5
	flush_size => 1000
	statement => [ "INSERT INTO question (content) VALUES(?)", "content"]
}
```

and here is the debug log:
![image](https://user-images.githubusercontent.com/17708548/49220791-1729bc80-f412-11e8-8792-fda18251d523.png)

I've also tried to remove the emoji in content, and this works, no exception.
![image](https://user-images.githubusercontent.com/17708548/49220909-74257280-f412-11e8-997a-575b099a58f0.png)

**Comment by silbertmonaphia** [comment]
Change `?useUnicode=yes&characterEncoding=UTF-8`  to `?useUnicode=true&characterEncoding=UTF-8` works. thx!
