### ISSUE TITLE
How to fix jdbc output :connection has passed maxLifetime

### ISSUE THREAD

**Issue by rkhapre** [theangryangel/logstash-output-jdbc#143]
Hi All
I am facing very strange issue of "connection has passed maxLifetime." 
I have a very large input which gives around 90,000 records, everything goes well on reading and filter operation, till the time it does the operation on filter, the output connection goes idles and timeout and hence i get the below error.
My output is Oracle DB

I see this is very common issue in HikariCP
I checked here
https://github.com/brettwooldridge/HikariCP/issues/883
it is recommending to keep this setting

> maximumPoolSize=40, minimumIdle=5, idleTimeout=30000

In my output configuration, i have kept 
connection_timeout => 10000000
and rest everything is default.
Please let me know how can i do setting on "idleTimeout" or is there any other solution for this

Below is the error
```
{
		"level" : "DEBUG",
		"loggerName" : "com.zaxxer.hikari.pool.PoolBase",
		"timeMillis" : 1546767196396,
		"thread" : "HikariPool-1 connection closer",
		"logEvent" : {
			"message" : "HikariPool-1 - Closing connection oracle.jdbc.driver.T4CConnection@1d573e39: (connection has passed maxLifetime)"
		}

	}
```

```
{
		"level" : "DEBUG",
		"loggerName" : "com.zaxxer.hikari.pool.HikariPool",
		"timeMillis" : 1546767314803,
		"thread" : "HikariPool-1 housekeeper",
		"logEvent" : {
			"message" : "HikariPool-1 - Pool stats (total=5, active=0, idle=5, waiting=0)"
		}
```

I am generating logs in json format.

I am sure many of you might have faced this issue, this is a good plugin, but need some way to move forward

**Comment by theangryangel** [comment]
Connection timeout is not the same as idle timeout. These are different configuration options (see https://github.com/brettwooldridge/HikariCP/blob/dev/README.md).

Currently there is no way to pass this to hikari cp. But it’s a simple 2 line patch. If you want to submit a PR please do so. Otherwise I’ll try and get around to it next week during a lunch hour and make a new release.

Alternatively if you can’t wait edit your copy of jdbc.rb and add the setIdleTimeout call underneath the setConnectionTimeout.

**Comment by rkhapre** [comment]
Hi, thanks for this link and suggestions, i think my setting should be for maxLifetime to 0 and i will have to playaround with idletimeout.
Let me try out this.

**Comment by rkhapre** [comment]
Configuration of **setmaxLifetime** is not working here.
Only i am able to configure **setIdleTimeout**

I have kept setIdleTimeout= 6000000, hoping my input read, filters will take good 40-60 to do opeartion till the time everything will be in idle position, and when it will resume for insertion, the idle ones will become active and will not come into situation of closed connection

**Comment by rkhapre** [comment]
Hi @theangryangel 
 After further running my pipeline, i can say confidently that pipeline does not work on more that 53 to 55 K records
I have set default pool size as 5, which keeps running and show logs as

> {"message":"HikariPool-1 - Pool stats (total=1, active=1, idle=0, waiting=0)"}

and finally it stops posting data to Oracle DB and i get this error

```
{
	"level" : "WARN",
	"loggerName" : "com.zaxxer.hikari.pool.HikariPool",
	"timeMillis" : 1546978202286,
	"thread" : "HikariPool-1 housekeeper",
	"logEvent" : {
		"message" : "HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m27s393ms195µs110ns)."
	}
}
```

I have no clue how to fix this,please suggest how to go about it

**Comment by rkhapre** [comment]
yes, i have checked this post multiple times, the server i am using is a very huge one 8 Core CPU and 60 GB RAM, i dont think resource is a problem
According to the logs, i see one by one all the connection in pool of 5 goes into ideal mode and finally dies out.
I am sure the connection which goes into idle to disconnected mode, never comes into active mode. This is what creates problem and when it tries to connect again then further i am getting this error

and this happens only after 52-53 K records

> {"level":"DEBUG","loggerName":"logstash.agent","timeMillis":1546978162927,"thread":"Ruby-0-Thread-22: /vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/server.rb:296","logEvent":{"message":"2019-01-08 12:09:22 -0800: Listen loop error: #<Errno::EBADF: Bad file descriptor - Bad file descriptor>"}}

Any idea on this
