### ISSUE TITLE
Getting error while inserting records into oracle using Logstash

### ISSUE THREAD

**Issue by Parkerkent** [theangryangel/logstash-output-jdbc#147]
Getting below issue : 
 Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Sequel::DatabaseConnectionError: Java::JavaLang::IllegalAccessError: tried to access class oracle.jdbc.driver.PhysicalConnection$BufferCacheStore from class oracle.jdbc.driver.PhysicalConnection>, :backtrace=>["java.lang.Class.getDeclaredClasses0(Native Method)", "java.lang.Class.getDeclaredClasses(java/lang/Class.java:1867)"

I am using jdbc input plugin, Jdbc_streaming in filter and jdbc output pluging too.
When I remove the jdbc output plugin I dont get any error.
Please help me.

**Comment by theangryangel** [comment]
What jar are you using in your output? Can you provide a sample config?

This plugin does not use `Sequel`, so I'm unclear on why you would be getting an error related to `Sequel::DatabaseConnectionError`.

**Comment by Parkerkent** [comment]
Thanks for the reply!
Please find the below sample config : 
input{
	jdbc {
	jdbc_validate_connection => true
        jdbc_connection_string => "jdbc:oracle:thin:@(database)"
        jdbc_user =>  ""
        jdbc_password => ""
        jdbc_driver_library => "ojdbc7.jar"
		jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
		lowercase_column_names => false
        jdbc_fetch_size => 1000
        sequel_opts => {"max_connections" => "10"}
        clean_run => true
        statement => "select query"
		}	
}
filter {

if([JOB_TYPE] == "something"){
mutate {
rename => {
                    "ID" => "id"
                }
 }
 jdbc_streaming {
 jdbc_validate_connection => true
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
              jdbc_driver_library => "ojdbc7.jar"
                jdbc_connection_string => "jdbc:oracle:thin:@(database)"
               jdbc_user => ""
               jdbc_password => ""
    statement => "select query"
       parameters => { "instance_id" => "instance_id"}
	  target => "array"
  }
 
ruby { code => '
     event.set("[@metadata][array]", event.get("array").length)
	 savas = Array.new
				if (event.get("array")!=nil && !event.get("array")[0].empty?)
					event.get("array").each{|h|
						if !h.empty?
							savaHash = Hash.new
							h.each {|k, v| 					  
								if(k == "id1")
									event.set("nwnccd",v)
								end
								
								if(k == "id2")
									event.set("nwncid",v)
								end
							}
							
						end
					}
				event.set("opType","U")		
				event.set("type",event.get("JOB_TYPE"))
				event.set("[@metadata][isNwncInsert]","true")
				event.set("source","something")
				event.set("errorCreateDate",event.get("@timestamp"))	
			end
			
'
}

mutate {
convert => {"nwncid" => "integer"}
convert => {"nwnccd" => "integer"}
}

}
}
output{
stdout { codec => rubydebug {metadata => true} }
if([@metadata][isNwncInsert]){
  jdbc {
                driver_class => "oracle.jdbc.driver.OracleDriver"
				driver_jar_path => "ojdbc7.jar"
				 connection_string => "jdbc:oracle:thin:@(database)"
               username => ""
               password => ""
               statement => ["insert into table ( id, col1, col2, col3) values(?,?,?,?)", "id", "opType", "source", "nwnccd"]
			   
          }
		  }
  }

**Comment by theangryangel** [comment]
From a quick look your config looks ok.. are you absolutely 100% sure this disappears without this plugin? It’s not something that’s coming up infrequently fine one of the others? Like I say this plugin does not use Sequel so I currently can’t see a reason why you’d get that error.

**Comment by Parkerkent** [comment]
Yes, when I remove the output plugin it works perfectly.
Even I am clueless why is this error coming up?
And one more thing...whenever I start my script without jdbc output plugin , it works and when I add jdbc output plugin back to the script while script is running then it works and inserts records in table as well.
This is strange behaviour.
