### ISSUE TITLE
ERROR: Installation Aborted, message: incompatible encodings: Windows-1254 and UTF-8

### ISSUE THREAD

**Issue by MasallahOZEN** [theangryangel/logstash-output-jdbc#148]
Hi, I give this error when install plugin on windows.

>bin/logstash-plugin install logstash-output-jdbc
Validating logstash-output-jdbc
Installing logstash-output-jdbc
ERROR: Installation Aborted, message: incompatible encodings: Windows-1254 and UTF-8

Thnx

**Comment by MasallahOZEN** [comment]
Logstash version (installed on win 10) : logstash-6.7.0

**Comment by theangryangel** [comment]
This is a logstash and/or environmental problem and not something I can fix.
