### ISSUE TITLE
Add connection string config file path

### ISSUE THREAD

**Issue by enriquerodbe** [theangryangel/logstash-output-jdbc#15]
I'm reading the database connection properties from a configuration file and putting them in an field in the event, using the ruby filter plugin.
Would it be difficult to add string interpolation to the connection string, so I can keep sensitive information out of my logstash.conf file?
I think the change would just be something like this:

    @connection = driver.connect(event.sprintf(@connection_string), java.util.Properties.new)
In this line: https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L74

Does that make sense?
Thanks.

**Comment by enriquerodbe** [comment]
I see that change is not possible because connection string is determined in the register phase.
What about another plugin parameter like "config_path" that points to a database.yml?

**Comment by theangryangel** [comment]
I'm happy to accept the pull request, if there's a reason I'm not seeing (forgive me if I am, but it's the end of the day here and I'm pretty tired :sweat_smile:)... but I'm not sure of the benefit?

My thinking; the user that logstash runs as will need to read the yaml file - so it's not like you're trying to prevent the logstash user from being able to read the credentials? As a matter of best practice I'd make sure that the logstash configuration should be reasonably secured anyway i.e. locked down to the account that logstash runs as.

If it's a case of ease of deployment, you should be able to template the logstash configuration using your deployment tool(s) - which negates the need for another configuration file.

I'm just trying to understand what I'm missing :smile:

**Comment by enriquerodbe** [comment]
Yes, I see. Looks like using templates is the way to go with logstash, since no other plugin has this feature.
Ok, sorry for the inconvenience and thanks for your time :)

**Comment by theangryangel** [comment]
No problem @enriquerodbe :smile: 

If there is a reasonable reason, other than just another config file I'm happy to accept the pull request. 

I know other plugins have considered supporting environment variables and string interpolation, but I don't know of any that currently do it. I'd be kinda fine with that personally, rather than another config file, but thats just me :laughing:

**Comment by theangryangel** [comment]
@enriquerodbe  - just as a FYI incase you missed it, Logstash now supports ENV vars  - https://www.elastic.co/blog/logstash-2-3-0-and-2-2-3-released
