### ISSUE TITLE
java.lang.VerifyError: Inconsistent stackmap frames at branch target 125

### ISSUE THREAD

**Issue by Parkerkent** [theangryangel/logstash-output-jdbc#150]
Please help me with the below issue .
Error description :
[2019-04-19T16:00:14,214][ERROR][org.logstash.Logstash    ] java.lang.VerifyError: Inconsistent stackmap frames at branch target 125
	Exception Details:
	  Location:
	    oracle/jdbc/driver/OraclePreparedStatement.setNullCritical(IILjava/lang/String;)V @125: aload_0
	  Reason:
	    Type 'oracle/jdbc/oracore/OracleTypeCOLLECTION' (current frame, locals[4]) is not assignable to 'oracle/jdbc/oracore/OracleTypeADT' (stack map, locals[4])
	  Current Frame:
	    bci: @99
	    flags: { }
	    locals: { 'oracle/jdbc/driver/OraclePreparedStatement', integer, integer, 'java/lang/String', 'oracle/jdbc/oracore/OracleTypeCOLLECTION', 'oracle/jdbc/driver/Binder', 'oracle/sql/ArrayDescriptor' }
	    stack: { }
	  Stackmap Frame:
	    bci: @125
	    flags: { }
	    locals: { 'oracle/jdbc/driver/OraclePreparedStatement', integer, integer, 'java/lang/String', 'oracle/jdbc/oracore/OracleTypeADT', 'oracle/jdbc/driver/Binder' }
	    stack: { }
	  Bytecode:
	    0x0000000: 013a 042a b400 6f3a 051c aa00 0000 0073
	    0x0000010: 0000 07d2 0000 07d9 0000 0034 0000 0048
	    0x0000020: 0000 0073 0000 0073 0000 002e 0000 005c
	    0x0000030: 0000 0034 0000 005c 2ab4 0073 3a05 2d2a
	    0x0000040: b400 b6b8 01c1 3a06 1906 b601 c23a 04a7
	    0x0000050: 002e 2d2a b400 b6b8 01c3 3a06 1906 b601
	    0x0000060: c43a 04a7 001a 2d2a b400 b6b8 01c5 3a06
	    0x0000070: 1906 b601 c6c0 00e4 3a04 a700 032a b400
	    0x0000080: ce1b 1905 532a b400 ffc7 0013 2a2a b400
	    0x0000090: bd2a b400 c0c5 0175 02b5 00ff 2ab4 00ff
	    0x00000a0: 2ab4 010c 321b 0153 1904 c600 0919 04b6
	    0x00000b0: 01c7 572a b401 01c7 0013 2a2a b400 bd2a
	    0x00000c0: b400 c0c5 0176 02b5 0101 2ab4 0101 2ab4
	    0x00000d0: 010c 321b 1904 532a b400 cf1b 1905 b401
	    0x00000e0: 194f 2ab4 00d1 1b03 4fb1               
	  Stackmap Table:
	    append_frame(@56,Object[#1458],Object[#1395])
	    same_frame(@62)
	    same_frame(@82)

**My configuration file as below :**

input{
    jdbc {
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
    jdbc_connection_string => "{{jdbc_connectstring}}"
    jdbc_user => "{{user_name}}"
    jdbc_password => "{{password}}"
    jdbc_driver_library => "{{driverjarpath_ojdbc7}}"
    jdbc_fetch_size => 1000
    connection_retry_attempts => 5
    connection_retry_attempts_wait_time => 1
    jdbc_validate_connection => true
    lowercase_column_names => false
    	statement => "select * from table"
 }
}

filter {
    
    mutate {
         add_field => {"source" => "Proecss"}
         add_field => {"falg" => "N"}
    }

    elasticsearch {
        hosts => {{ host}}
        index => "index_es"
        query => "id:%{[id]}"
        fields => {"id" => "id"}
        enable_sort => false
        user=>"{{user}}"
        password=>"{{pwd}}"
		
    }
}

output{    

   if(!([id]) and !("_elasticsearch_lookup_failure" in [tags])){
          
         elasticsearch{
            hosts => {{ host}}
            action => "index"
            index => "index-%{+YYYY.MM.dd}"
            timeout => {{ logstash_es_timeout }}
        }
        
        jdbc {
                driver_class => "oracle.jdbc.driver.OracleDriver"
				driver_jar_path => "{{driverjarpath_ojdbc7}}"
               connection_string => "{{jdbc_connectstring}}"
               username => "{{euser_name}}"
               password => "{{password}}"
               max_pool_size => 10
               driver_auto_commit => true
			   statement => ["insert into Table1 (ID,ID1) values(?,?)","ID","ID1"]
			   
          }
        jdbc {
                 driver_class => "oracle.jdbc.driver.OracleDriver"
				driver_jar_path => "{{driverjarpath_ojdbc7}}"
               connection_string => "{{jdbc_connectstring}}"
               username => "{{euser_name}}"
               password => "{{password}}"
               max_pool_size => 10
               driver_auto_commit => true
			   statement => ["insert into Table2 (ID,ID1) values(?,?)","ID","ID1"]
               
          }
          
    }
}

**Comment by theangryangel** [comment]
I would start off by checking you’re using an appropriate version of the oracle jdbc driver for the java version you are using.
