### ISSUE TITLE
Issue when using the input and output jdbc plugin in the same conf file

### ISSUE THREAD

**Issue by jorgemarqrent** [theangryangel/logstash-output-jdbc#153]
Hi, i have an issue with using both the input and output jdbc plugins in the same pipeline. At first everything went well and worked as expected, but when I tried to execute the pipeline again to insert more rows into the table some errors popped up and nothing was inserted.

I'm using **logstash 6.2.4** with the logstash-output-jdbc **plugin version 5.4.0** pointing to a **MySQL 5.7** Database and the **mysql-connector-java-5.1.38**

This is my config file

```
input {
    jdbc {
        jdbc_connection_string =>"jdbc:mysql://host:port/db"
        jdbc_user => "user"
        jdbc_password => "pass"
        jdbc_driver_library => "/usr/share/java/mysql-connector-java-5.1.38.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        statement_filepath => "/path/to/statement.sql"
    }
}

filter {
    translate {
        field => "testproject"
        destination => "testproject"
        dictionary_path => "/path/to/proy_dict.yml"
        override => true
    }
    grok {
        match => 
        {"testproject" => "%{DATA:project_id}-(\s)?%{GREEDYDATA:project_name}"}
    }
    if [execution_type] == 10 {
        mutate {
            replace => {"execution_type"=>"m"}
        }
    } else {
        mutate {
            replace => {"execution_type"=>"a"}
        }
    }
}

output {
    stdout {
        codec => rubydebug 
    }
    jdbc {
        driver_jar_path => "/usr/share/java/mysql-connector-java-5.1.38.jar"
		driver_class => "com.mysql.jdbc.Driver"
		connection_string => "jdbc:mysql://host:port/db?user=user&password=pass"
		statement => [ "INSERT INTO vt_TestExecutions ( ProjectId,ReleaseCode, TestCycleId, SuiteId, StartDate, EndDate, TestType) VALUES(?, left(?,5), ?, ?, ?, ?, ?)",
         "project_id", "build", "id", "testsuite_id", "execution_ts", "execution_ts", "execution_type" ]
	}
}
```
All fields needed were present in the events.

I tried putting the jar for the connector in **$LOGSTASH_HOME/vendor/jar/jdbc/** and also changing to another connector version but still didn't worked and these gave me another errors related to the classes in the jdbc connector.
When I disable the logstash-output-jdbc plugin I don't get any error so I think that its all related to it.

These are the errors I've seen when trying to execute the pipeline 

 With the config file as seen above
```
[2019-06-11T12:18:09,081][ERROR][logstash.inputs.jdbc     ] Unable to connect to database. Tried 1 times {:error_message=>"Java::JavaLang::IllegalAccessError: tried to access class com.mysql.jdbc.ConnectionPropertiesImpl$XmlMap from class com.mysql.jdbc.ConnectionPropertiesImpl"}

```
 
With the connector in **$LOGSTASH_HOME/vendor/jar/jdbc/**
```
[2019-06-11T12:20:01,856][ERROR][org.logstash.Logstash    ] java.lang.NoClassDefFoundError: Could not initialize class com.mysql.jdbc.PreparedStatement
```

**Comment by theangryangel** [comment]
As a starting point please double check you are using an appropriate mysql jdbc jar for your version of java. You didn’t tell me what you’re using but the one you’re using is 4 years old and not current at all... I haven’t kept up to date with JDBC changes but there is a distinct possibility that it’s simply incompatible. 

If that doesn’t work - 

Your first error is coming from the input plugin (it’s prefixed by the [logStash.inputs.jdbc]. Not this one. I don’t see how the output plugin can affect the input atm... it is possible you’ve simply not got any data to pass through when you’re disabling this plugin as a test? If you leave stdout as a an output does it work and do you get data output to the console? The second error is a bit vague and unhelp and could be either.. so I’m gonna ignore that one for a second.

**Comment by jorgemarqrent** [comment]
I changed the jdbc for this plugin with the **8.0.16** version but kept the older version for the other jdbc plugins and everything worked as expected.

Thanks for the advice and sorry for bringing this up before making more tests.
