### ISSUE TITLE
call store procedure from oracle with output sys_refcursor

### ISSUE THREAD

**Issue by RiPav** [theangryangel/logstash-output-jdbc#155]
Hello,
I created some procedure in oracle database aum which return sys_refcursor.
create or replace procedure aum
IS
v_code NUMBER;
v_errm VARCHAR2(200);
rc sys_refcursor;
BEGIN
open rc for select username from f=dba_users;
dbms_sql.return_result(rc);
EXCEPTION
WHEN OTHERS THEN
v_code := SQLCODE;
v_errm := SUBSTR(SQLERRM, 1, 200);
DBMS_OUTPUT.PUT_LINE (v_code || ' ' || v_errm);
END;
/

My configuration in logstash is
input {
jdbc {
jdbc_validate_connection => true
jdbc_driver_library => "/etc/logstash/ojdbc8.jar"
jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
jdbc_connection_string => "jdbc:oracle:thin:@//xxxxxcom:1521/xxx"
jdbc_user => "system"
jdbc_password => "xxxxx"
statement => "{call system.aum}"
schedule => "*/3 * * * *"
}
}
output {
file {
path => "/tmp/my_out_file3.txt"
codec => "rubydebug"
}
}

Is't possible to see result set from DB send to file ?
I see from log logstash, that call was, but file is empty.
Thanks for any advice or comment
Richard

**Comment by theangryangel** [comment]
Your configuration isn't using logstash-output-jdbc? Did you mean to log
this against logstash-input-jdbc (
https://github.com/logstash-plugins/logstash-input-jdbc)? They're 2
different projects :)

**Comment by RiPav** [comment]
Thanks, I am beginner with logstash.
I need call some store procedure in oracle DB by logstash, which return data as some result data set.
These data insert into file for example to /tmp/file.
Is't possible ?

logstash-output-jdbc - it means , that i want to insert data to DB, but i want data from DB ?? 

Richard

**Comment by theangryangel** [comment]
This project (logstash-output-jdbc) is for writing data to a database.

logstash-input-jdbc is for reading data from a database.

I don't use the input plugin, but in theory as long as you're returning a record set from your procedure I don't see why it wouldn't work... But like I say, I don't use logstash-input-jdbc.

**Comment by RiPav** [comment]
Thanks, i try to ask logstash-input-jdbc project.
Richard
