### ISSUE TITLE
Connection not close when not have new data in a long time

### ISSUE THREAD

**Issue by annony-zx** [theangryangel/logstash-output-jdbc#156]
Hi all,

I use logstash to push data from csv to mysql with bellow config:

>       max_pool_size => 20
>       connection_timeout => 10000
>       retry_initial_interval => 3
>       retry_max_interval => 60

when not have new data in a log time, connection in mysql server not auto close and still at sleeping.

Can you help me resolve it ?
Thank you.

**Comment by theangryangel** [comment]
The plugin uses HikariCP to maintain a pool of connections. As the timeout is reached the existing connection should be closed and a new one created... This is intentional as it allows the plugin to not have to perform a logon every time there's new data... Whats the actual problem you're having?

**Comment by annony-zx** [comment]
I think it always maitain a lot of connection to MySQL server is not good for my server and now i understand. I will close issue now.
Thank for helping.

**Comment by theangryangel** [comment]
If you have too many open reduce the max pool size 👍🏻
