### ISSUE TITLE
Closed Connection Exception

### ISSUE THREAD

**Issue by shravan521** [theangryangel/logstash-output-jdbc#19]
The database connection is getting closed after it ran for few hours (don't follow a pattern).
I will need to infinitely run the logstash and insert the required fields into the database using the 
logstash-output-jdbc plugin in output.

Below is the trace:
{:timestamp=>"2015-11-09T11:26:22.870000-0500", :message=>"Failed to flush outgoing items", :outgoing_count=>21, :exception=>java.sql.SQLRecoverableException: Closed Connection, :backtrace=>["oracle.jdbc.driver.PhysicalConnection.prepareStatement(oracle/jdbc/driver/PhysicalConnection.java:3587)", "oracle.jdbc.driver.PhysicalConnection.prepareStatement(oracle/jdbc/driver/PhysicalConnection.java:3488)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)", "LogStash::Outputs::Jdbc.flush(/home/oracle/Logstash/logstash-1.5.3/vendor/local_gems/97ce7616/logstash-output-jdbc-0.1.1/lib/logstash/outputs/jdbc.rb:104)", "LogStash::Outputs::Jdbc.flush(/home/oracle/Logstash/logstash-1.5.3/vendor/local_gems/97ce7616/logstash-output-jdbc-0.1.1/lib/logstash/outputs/jdbc.rb:104)", "Stud::Buffer.buffer_flush(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219)", "Stud::Buffer.buffer_flush(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219)", "org.jruby.RubyHash.each(org/jruby/RubyHash.java:1341)", "Stud::Buffer.buffer_flush(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216)", "Stud::Buffer.buffer_flush(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216)", "Stud::Buffer.buffer_flush(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:193)", "Stud::Buffer.buffer_flush(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:193)", "RUBY.buffer_initialize(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:112)", "org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1511)", "RUBY.buffer_initialize(/home/oracle/Logstash/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:110)", "java.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:warn}

Here is my logstash config file.
[trace.txt](https://github.com/theangryangel/logstash-output-jdbc/files/31234/trace.txt)

**Comment by theangryangel** [comment]
I have 2 instances running in production for weeks at a time without any issue - although I do have them connecting to SQL server rather than Oracle. 

Have you ruled out transient connectivity issues with the oracle server?

**Comment by theangryangel** [comment]
I suppose thinking about it the output plugin should really have connection pooling support.

I'll have a thing about how to introduce this tomorrow.

In the meantime my existing comment does stand 😁

**Comment by shravan521** [comment]
Thank you for the quick reply. Connection pooling support would be awesome.
For transient connectivity issue, is there any known solution to keep the connection alive when not it in use?(Off course I don't like to trap the connections when not in use, pooling is the best option).

**Comment by theangryangel** [comment]
As a temporary measure try adding the autoreconnect parameter to the connection string. It may help out.

I'm hoping to have sometime this weekend to try out connection pooling.

**Comment by shravan521** [comment]
Sure.. Thank you!
Since I am using Oracle,  i have added a parameter ENABLE=broken to enable the keepAlive feature of the connection string.

**Comment by theangryangel** [comment]
I've just pushed 0.2.0.rc1to rubygems. Can you give it a go and see how you get on? It seems stable to me, but I've not got any Oracle boxes around that I can test on.

You'll probably need to uninstall the existing version, and then install using `./bin/plugin install logstash-output-jdbc 0.2.0.rc1`

For reference, this version adds a couple of extra configuration parameters for tuning the connection pool:
  - max_pool_size - maximum number of connections in the pool at any 1 time. I've defaulted this to 5 for now.
  - connection_timeout - how long before it drops a connection (in seconds) - 10 minutes at the moment

I've also added extra fields for supplying the username and password separately, as I'm led to understand with some jdbc drivers its not possible to supply them in the url.

**Comment by shravan521** [comment]
Thank you for making the changes quickly. 
But I see the following error while trying to install using the 
bin/plugin install logstash-output-jdbc-0.2.0.rc2.gem 

  [oracle@hercules logstash-2.0.0]$ bin/plugin install logstash-output-jdbc-0.2.0.rc2.gem 
Validating logstash-output-jdbc-0.2.0.rc2.gem
Installing logstash-output-jdbc
Error Bundler::GemspecError, retrying 1/10
There was a Errno::ENOENT while loading logstash-output-jdbc.gemspec: 
No such file or directory - git from
  /media/sf_MyShared/logstash-2.0.0/vendor/local_gems/bb02a80a/logstash-output-jdbc-0.2.0.rc2/logstash-output-jdbc.gemspec:13:in `eval_gemspec'

Am I missing something?

Regards,
Shravan

**Comment by theangryangel** [comment]
Try the command `bin/plugin install --version 0.2.0.rc2 logstash-output-jdbc` - it should down and install from rubygems directly and do all the necessary. You shouldn't have to download the gem manually.

If it doesnt work what OS are you installing on?

**Comment by shravan521** [comment]
Perfect! This command worked fine. Moving forward I will have to install this on a server which will not have access to external websites, I will need a local gem to install on the machine. 
FYI, I am using Oracle Linux OS!

**Comment by shravan521** [comment]
Thanks a lot! The issue seems to be fixed.
Please let me know which command should I use to install the plugin using a local gem.

**Comment by theangryangel** [comment]
Can you try downloading rc3 from [rubygems](https://rubygems.org/downloads/logstash-output-jdbc-0.2.0.rc3.gem) and then issuing a `bin/plugin install logstash-output-jdbc-0.2.0.rc3.gem`? I'm guessing the lack of git on your box is causing the problem. I've switched to using a different method for determining which files to bundle in the gem.

**Comment by shravan521** [comment]
logstash-output-jdbc-0.2.0.rc3.gem did successfully install. Thank you once agian.

**Comment by shravan521** [comment]
After updating to 0.2.0.*, when logstash is executed the fields that doesn't have values started inserting Tag names(of which we are capturing) instead of null(which was doing in previous version).

**Comment by theangryangel** [comment]
Ah. Bugger 😕. I was hoping no one was relying on that functionality as it wasn't intended and was accidental. That said I do see the usefulness of it, so I'll add it back in.

I'll have a patch/and another rc fixing this tomorrow morning.

**Comment by shravan521** [comment]
Sure. That would be great!

**Comment by shravan521** [comment]
Hello! Sorry to bug you.. I am kind of stuck without this patch. Any possibility to have it soon?

**Comment by theangryangel** [comment]
Ive just built and pushed rc4 to rubygems. Give that a go.

Sorry I've not had a chance to test this release. I've been sick the last few days and having issues looking at computer screens =/

**Comment by shravan521** [comment]
I feel bad for troubling you.. Hope you get well soon.
I have installed rc4 and ran a sample it broke something i guess and throws the following error:

SystemStackError: stack level too deep
            each at org/jruby/RubyHash.java:1342
    buffer_flush at /media/sf_MyShared/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216
  buffer_receive at /media/sf_MyShared/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159
         receive at /media/sf_MyShared/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.0.rc4/lib/logstash/outputs/jdbc.rb:109
          handle at /media/sf_MyShared/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80
     output_func at (eval):107
    outputworker at /media/sf_MyShared/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:252
   start_outputs at /media/sf_MyShared/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:169

**Comment by theangryangel** [comment]
I've just released 0.2.0-rc5 which should fix this problem.

Sorry about that :sweat_smile:

**Comment by theangryangel** [comment]
I've just released 0.2.1 proper with this in.

I don't believe there are any faults or bugs, but if you come across something I've missed please do let me know and I'll get it sorted for you.

**Comment by shravan521** [comment]
Thank you so much! It looks all good now.
