### ISSUE TITLE
Untested with other JDBC drivers

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/logstash-output-jdbc#2]
Known working SQL engines (note: these may not all yet be actively tested on every release). Example configurations can be found in the examples/ directory.
  - DerbyDB
  - Apache Phoenix
  - MariaDB
  - MySQL
  - odps
  - Oracle
  - Postgres
  - Microsoft SQL Server
  - SQLite

If you'd like to add to this list, we do accept pull requests.

**Comment by roflmao** [comment]
Trying to test with PostgreSQL JDBC driver:

```
{:timestamp=>"2015-05-19T12:57:03.160000+0200", :message=>"JDBC Exception", :exception=>java.sql.BatchUpdateException: Batch entry 0 INSERT INTO log (host, timestamp, message) VALUES('host', '@timestamp', 'message') was aborted.  Call getNextException to see the cause., :level=>:error
```

How can i call the getNextException in the plugin?

**Comment by theangryangel** [comment]
I'll be honest, I don't often use postgres, but from a cursory glance it looks like it's JDBC driver works slightly differently when it comes to exceptions. I had assumed all drivers worked the same.

The only way would be to modify the code of the plugin right now.

Try swapping out [line 126](https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L126) for something like this (I've not tested this as I'm in the middle of something else, but it should probably work):

```
loop do
   @logger.warn("JDBC - Exception", :exception => e)
   e = e.getNextException()
   break unless e
end
```

**Comment by roflmao** [comment]
Excellent! Thanks. Got the error message so now i have the PostgreSQL driver working :)

**Comment by roflmao** [comment]
```
    jdbc {
        driver_class => 'org.postgresql.Driver'
        connection_string => 'jdbc:postgresql://hostname:5432/database?user=username&password=password'
        statement => [ "INSERT INTO log (host, timestamp, message) VALUES(?, CAST (? AS timestamp), ?)", "host", "@timestamp", "message" ]
    }
```

**Comment by theangryangel** [comment]
Awesome. I'll add in some better exception handling when I have a chance in the next few days.

Out of interest, what version of logstash are you running against at the moment? I've not checked the plugin with 1.5 myself yet :smile:

**Comment by roflmao** [comment]
Im still using 1.4.2. Im afraid the plugin needs abit of work for 1.5 plugin system?
Would be awesome for this plugin to be pushed to logstash-plugins with 1.5 support!

**Comment by theangryangel** [comment]
@roflmao the plugin now supports 1.5. I've not gone looking into the logstash-plugins org yet, but it is installable through the normal bin/plugins method under 1.5.

**Comment by roflmao** [comment]
Will test it when i upgrade to 1.5. Great stuff!

**Comment by tyb1222** [comment]
why do I get an error 
"[root@tao ~]# cd /software/logstash-1.5.2
[root@tao logstash-1.5.2]# ./bin/plugin install logstash-output-jdbc
Validating logstash-output-jdbc
Unable to download data from https://rubygems.org/ - Connection reset by peer (https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)
ERROR: Installation aborted, verification failed for logstash-output-jdbc
"

**Comment by theangryangel** [comment]
@tyb1222 it looks like your connection to rubygems.org is having issues. This isn't a problem with the plugin, or logstash. Just your connection.

I can only suggest either:
1. Retrying
2. Downloading from https://github.com/theangryangel/logstash-output-jdbc/tree/v1.5 (since you're using 1.5?) and copying the lib directory contents into your logstash installations lib directory

**Comment by tyb1222** [comment]
I will try again .thank you

**Comment by tyb1222** [comment]
@theangryangel  I will try again .thank you
