### ISSUE TITLE
Ability to use fields inside sql statement (not just for column values)

### ISSUE THREAD

**Issue by db2882** [theangryangel/logstash-output-jdbc#20]
First off, thanks for the awesome plugin! 

I was hoping to use a field value ("table_name") to control what table an event is inserted into. As it currently stands, the plugin just passes the 0th string as the sql so something like "INSERT INTO %{table_name}" gets taken literally. 

As I understand it, this is how prepared statements work so the @statement[0] would have to be parsed ahead of time. Do you think this would be prohibitively slow? Maybe it could take the string literally by default, but parse for field values if a certain configuration option was set.

I am relatively new to the logstash world so I'll defer to you, but if you think something like this would work, let me know and I would be happy to write it.

**Comment by theangryangel** [comment]
The only reason it's really prepared ahead of time and reused was because of how it worked before 1.5. Performance wise it's probably negligible.

My worry would be one of security. We could format the statement and allow the sql to be dynamic but it's a point of injection and could be used maliciously.

Depending on how many values your field could have, I would probably more simply have multiple jdbc outputs and if statements to send your events to different ones.

However it's pretty unmaintainable with large numbers of values.

Equally by formatting the query string it would be possible for attempted insertions into non-existing tables. This would result in the exception handling (which is dumb arm) to retry each event several times (configurable).

Sorry for the wall of text, but I'm just dumping my brain into the screen tonight 😅

**Comment by db2882** [comment]
Quick response!

Yeah after reading what you said I realized I was being pretty short sighted in terms of security. In my use case I knew exactly where the logs were coming from and what they contained, but I agree; blindly executing logstash data as sql is just asking for trouble.

**Comment by theangryangel** [comment]
I'm in 2 minds whether or not to support this tbh.

When I look into #19 I'll have to change how the statement is prepared anyway. So, I can add it when I look at the connection pooling stuff... Buuuuut. I'm hesitant tbh. 

On top of the security issues JDBC doesnt expose any way to quote things like table and column names, so it could be super unreliable if anything like spaces come through in the logs, and the statement isn't quite right.

Are you adding a field in your logstash config? Or is it coming directly from the logs? I suppose what I'm asking is can you convince me? ;)

**Comment by db2882** [comment]
The short answer: After your initial comment I don't think I'm trying to convince you anymore. I think you're right with your two points about security and unreliability.

The slightly longer answer: Here was my use case that motivated me to open this issue: I am receiving logs that logstash then routes to graylog for easy querying and also to a backup mariadb database (which works btw if you want to add it to your tested databases). The logs are stored in tables based on a combination of there data and source. There are just enough combinations that having multiple jdbc outputs isn't super elegant. I ended up simply writing them to one core table and then running some scheduled stored procedures to reroute them on the database side. Not super elegant, but it works. Basically the take away from me should be that if I'm the only one who requested this feature, it probably isn't worth the time to implement given the security and unreliability costs associated with it. If other people are looking for this feature, however, it might be cool to have a boolean flag that defaults to false but when set to true parses the sql for fields. This way people could judge whether the risk was acceptable on a case by case basis.

**Comment by theangryangel** [comment]
I've added support in the 0.2.0.rc2.

Example configuration:
```
input {
	stdin { }
}
filter {
    mutate {
        add_field => { "table_name" => "log" }
    }
}
output {
	stdout { }

	jdbc {
		connection_string => 'jdbc:sqlite:test.db'
        unsafe_statement => true
		statement => [ "INSERT INTO %{table_name} (host, timestamp, message) VALUES(?, ?, ?)", "host", "@timestamp", "message" ]
	}
}
``` 

Can you give it a test please, and see how you get on with it?

If you do a `bin/plugin install logstash-output-jdbc 0.2.0.rc2` you should get the correct version. Note that this version also includes connection pooling, and that the driver_class statement is no longer required. So any weird problems may be related to those changes as well.

If everything is good, I'll release an update some time Monday when I can test with a few other SQL drivers.

**Comment by db2882** [comment]
Hey sorry to just be getting back to you. When I try installing the the new version I'm getting an error saying that the "Plugin 0.2.0.rc2 does not exist". I just want to confirm that the install command you gave above has the correct version name.

**Comment by theangryangel** [comment]
Sorry. I mangled the command. It should be `bin/plugin install --version 0.2.0.rc2 logstash-output-jdbc`

**Comment by db2882** [comment]
Just got a chance to test it. Sorry for the delay. Seems to be working as expected! Thanks a bunch.

**Comment by theangryangel** [comment]
Glad to hear it. Bear in mind that there is a performance penalty in using this mode. It's only able to insert 1 event per query, whereas the "safe" mode is able to insert multiple events at the same time.

I'll leave it a few days, if you have any problems, let me know. If not I'll do a full release before the end of the week.

**Comment by delatitude** [comment]
hello. thanks for this plugin. is this feature in the latest version ? when i try to replace table_name it never works and returns error.

**Comment by theangryangel** [comment]
Yes - https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L220

However, it depends on the logstash event.sprintf function, so if elastic have changed that it may be broken.

If you're 100% sure that this isn't working and there's not some other mistake either open a new issue, or reopen this one, and I'll get to it when I can.
