### ISSUE TITLE
MariaDB Connection issues

### ISSUE THREAD

**Issue by wroberts15** [theangryangel/logstash-output-jdbc#28]
Wondering if there is a way to test the connection string to the database, is that possible? 

Using MariaDB with the JAR in vendor/jar/jdbc with the jar in your example and basically the same connection string. I am getting this output in my logstash.log

{:timestamp=>"2016-01-06T16:44:06.699000-0500", :message=>"The error reported is: \n  Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 2800ms."}

Kind of stuck on this, any help would be appreciated..

**Comment by ebuildy** [comment]
Hello, you could try the JDBC connection with a simple Java class instead:

https://gist.github.com/ebuildy/e0dbdaa463e07576043c

Compile the class with your JAR and Hikari JAR:

````
javac -cp .....JAR1:...JAR2 Test.java
````

**Comment by wroberts15** [comment]
Basically my connection string was fine, just had an incorrect path to my logs, so it was giving me this error. If anyone else has this issue and is sure that everything is set up correctly, double check minor things, i.e. path to logs/permissions as this error wasn't 'descriptive'

**Comment by theangryangel** [comment]
@wroberts15 can you give me a bit more info on this? I'd like to try and clear up the error message if I can, and save someone some pain down the line. However I'm not able to replicate the problem :disappointed: 

I've tried pointing my test logstash at inputs which aren't valid and I can't get hikari to throw any errors about failing to connect.

**Comment by wroberts15** [comment]
It was quite literally the path to my log file being incorrect, e.g. 

    input { 
          file { 
            path=> "/this/was/incorrect/logfile"


Not sure if maybe something else was also affecting it, but let me know if you still can't reproduce. As I previously mentioned, all the JAR files and configurations for this plugin were correct, as far as I know.

**Comment by wroberts15** [comment]
And I would say it's not like the error message was incorrect, it was just difficult in determining the issue..

**Comment by ljcastro** [comment]
Hi all,

Does the plugin work with Logstash 2.2.0? I've installed the plugin on two machines, one with Logstash 2.0.0 and the other with 2.2.0, and although both have the same configuration, with the Logstash newer version doesn't work. It shows me the "pool initialization" exception

**Comment by theangryangel** [comment]
I've not yet tested with 2.2, so honestly don't know.

I'll try and make some time today.

**Comment by ljcastro** [comment]
Ok thanks! I'll check if something important has changed from one version to another.

**Comment by theangryangel** [comment]
Looking at the changelog for 2.2 the only thing I can see that jumps out at me immediately is the change to a different version of jruby-openssl. The rest seems like it shouldnt make a difference.

Are you connecting to Maria using SSL by any chance?

**Comment by ljcastro** [comment]
Well, I'm connecting to SQL Server (sorry, I haven't said that), but I'm not using SSL. I've replied this issue because I think it's the same problem.

**Comment by ljcastro** [comment]
I've checked now the 2.1.2 version of Logstash, and it works seemlessly.

**Comment by ljcastro** [comment]
Nop... it doesn't work... sometimes it connects, but throws this exception:

`Failed to flush outgoing items {:outgoing_count=>1, :exception=>"Java::ComZaxxerHikariPool::HikariPool::PoolInitializationException", :backtrace=>["com.zaxxer.hikari.pool.HikariPool.initializeConnections(com/zaxxer/hikari/pool/HikariPool.java:535)", "com.zaxxer.hikari.pool.HikariPool.<init>(com/zaxxer/hikari/pool/HikariPool.java:137)", "com.zaxxer.hikari.HikariDataSource.getConnection(com/zaxxer/hikari/HikariDataSource.java:94)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "RUBY.safe_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.1/lib/logstash/outputs/jdbc.rb:168)", "RUBY.flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.1/lib/logstash/outputs/jdbc.rb:116)", "RUBY.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219)", "org.jruby.RubyHash.each(org/jruby/RubyHash.java:1342)", "RUBY.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216)", "RUBY.buffer_receive(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159)", "RUBY.receive(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.1/lib/logstash/outputs/jdbc.rb:109)", "RUBY.handle(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80)", "RUBY.output_func((eval):490)", "RUBY.outputworker(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:252)", "RUBY.start_outputs(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:169)", "java.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:warn}`

Any idea?

**Comment by theangryangel** [comment]
I've got 2.1 running in production against SQL Server 2008 R2, without issue.

Can you provide your JDBC output configuration please so I can try and replicate the problem?

**Comment by ljcastro** [comment]
I simply use: 

```
jdbc {
          connection_string => "jdbc:sqlserver://IPHERE:1433;databaseName=DB;user=USER;password=PASSWORD;autoReconnect=true;"
          statement => [ "INSERT INTO TABLE (column1,column2,...) VALUES (val1,val2,...)" ]
}
```
I have been using this configuration for 4 months without problems, but in a virtual machine. Now, I have installed a physical one, and surprisingly, it doesn't work anymore...

**Comment by ljcastro** [comment]
Testing with logstash 2.2 and the lastest plugin version, I've increased the connection timeout in the jdbc.rb file. For some reason, sometimes it throws a timeout error, but my SQL server is only working with logstash, this server is not in production yet.

Now with the increased timeout, it connects without problems. I'll keep watching it.

**Comment by theangryangel** [comment]
Is this https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L47 the timeout you modified @ljcastro? 

If so, can I ask what you modified it to? And did you know you can just change your connection configuration to (for example if you wanted a 5 second timeout), rather than changing the plugin itself :smile: 
```
jdbc {
          connection_string => "jdbc:sqlserver://IPHERE:1433;databaseName=DB;user=USER;password=PASSWORD"
          connection_timeout => 5000
          statement => [ "INSERT INTO TABLE (column1,column2,...) VALUES (val1,val2,...)" ]
}
```

With the connection pool functionality in the 2.x versions, I would avoid the autoReconnect parameter as it shouldn't be needed (in theory).

**Comment by ljcastro** [comment]
Aaaaargggghh!!! I was desperate and I overlooked that configuration option! Sorry!!! :-)

I'll try without the autoReconnect option and I'll comment you.

**Comment by theangryangel** [comment]
No need to be sorry :sweat_smile: Just thought you might want to know!

Do let me know what you set it to, so I can make it a more sensible default than 2 seconds :smile:

**Comment by ljcastro** [comment]
Now I'm using 5000 as connection timeout, and it works without issue.

**Comment by theangryangel** [comment]
Ok, I think I see why this is a problem, and why that fixes it. Thank you @ljcastro for having the time to look into this when I didn't :heart: 

For anyone else that may be affected by this bug (which may have affected any server) - I've pushed an update to rubygems. You can upgrade by issuing `bin/plugin update logstash-output-jdbc` from your logstash installation directory.

**Comment by ljcastro** [comment]
You welcome! Thank you for your work. It's a great plugin!
