### ISSUE TITLE
Losing Events when Server is down

### ISSUE THREAD

**Issue by githubmui** [theangryangel/logstash-output-jdbc#36]
Hi,
I have faced a big problem:
If the JDBC-Server is down then I am losing all the logstash events until the server is again up an running. (FYI: I am using this nice plugin in combination with the Crate JDBC connector)

What can be done against that?
Is it possible to configure or introduce somthing like a retry policy?
It would be great, if this plugins is as robust as the elasticsearch-output-plugin.
And currently, this is the best and fastest plugin to write data from Logstash into the Crate-Elasticsearch-DB. The http-output-plugin is slow and has got no retry policy at all!

Thx for writing this plugin and hopefully you can give me a hint or even a solution!

**Comment by theangryangel** [comment]
What version of logstash and the plugin are you using please? The reason I ask is because several versions ago the plugin was altered so that it should, keep inifinitely retrying everything in the buffer, unless you tell it not to.

**Comment by theangryangel** [comment]
Actually, I have thought of an obvious reason why this probably would happen on the current version as well :oops:

I'll try and make some time to test things tonight, or tomorrow - but it would still be useful to know version of the plugin you're using :smile:

**Comment by theangryangel** [comment]
I've pushed a release candidate that I think will resolve the problem for you in logstash 2.x.

Install (or update) using the command to specifically install this pre-release, and let me know if it fixes the problem for you please @githubmui 

``bin/plugin install --version 0.2.6.rc1 logstash-output-jdbc``

**Comment by theangryangel** [comment]
FYI @githubmui 0.2.6 (non-rc) is now on rubygems. There is a secondary fix included which may also resolve this problem. I've not been able to reproduce the issue since applying these 2 fixes.

**Comment by theangryangel** [comment]
If you can reproduce the original issue, please let me know.
