### ISSUE TITLE
MSSQL Always-on

### ISSUE THREAD

**Issue by phr0gz** [theangryangel/logstash-output-jdbc#37]
Hello, wonderful plugin thanks! does it works with MS SQL Always-On cluster? [https://msdn.microsoft.com/en-us/library/gg558121%28v=sql.110%29.aspx
](https://msdn.microsoft.com/en-us/library/gg558121%28v=sql.110%29.aspx
)

**Comment by theangryangel** [comment]
In theory, I don't see why not. However this isn't something I've tested the plugin with.

I'm afraid I don't have the opportunity to test this for you, so if you do have access to such an environment, my suggestion would be to configure the connection string as per that link, and try some dummy data with it to see if it works properly. 

I would love to know if it does. But, if it doesn't, let me know what problems you're seeing and I'll see if we can fix them :smile:

**Comment by phr0gz** [comment]
It's working like a charm :) great job!

**Comment by phr0gz** [comment]
Btw: I've used one listener with two IP (one IP per site)

**Comment by theangryangel** [comment]
❤️ Thank you for the feedback, really appreciate it :smile: I'll add a link pointing at this issue, to the SQL Server example

**Comment by theangryangel** [comment]
Note added in 26a32079f1b7fe111aab4c7d504faaca21c0d4f6
