### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by seanshihny** [theangryangel/logstash-output-jdbc#41]
Why installation failed with following error?

Installing logstash-output-jdbc
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-output-jdbc (0.2.7), and Bundler cannot continue.
Make sure that `gem install logstash-output-jdbc -v '0.2.7'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported

**Comment by theangryangel** [comment]
I have no idea. Do other plugins install?

**Comment by theangryangel** [comment]
Looking at https://github.com/logstash-plugins/logstash-filter-aggregate/issues/20 suggests that warning doesn't matter much.

Are you able to retry the plugin install command? And are you able to get to rubygems.org?

**Comment by seanshihny** [comment]
Yes I am able to install other plugins

**Comment by theangryangel** [comment]
Can you try downloading the gem manually (
https://rubygems.org/downloads/logstash-output-jdbc-0.2.7.gem) and then run logstash-plugin install path/to.gem?

If that doesn't work can you let me know what OS your installing on (including version), what version of logstash you're using, and what version of Java you have?

**Comment by seanshihny** [comment]
Your method worked and the plugin is installed successfully.

**Comment by theangryangel** [comment]
Sounds like connectivity issues to rubygems.org in that case 😄
