### ISSUE TITLE
call SP (stored procedure)

### ISSUE THREAD

**Issue by starlessboi** [theangryangel/logstash-output-jdbc#42]
Hi
first, thanks for great job you done.
I have a question, can I use this plugin to call sp in mssql server?
Thanks

**Comment by theangryangel** [comment]
In theory, I don't see why not, although I've not tested it. 

Something like the following will probably work. Example assumes procedure_name is in the default schema (dbo) and has 3 parameters, which host, timestamp and message is passed to it. None of which are optional.

```
jdbc {
    connection_string => "jdbc:sqlserver://server:1433;databaseName=databasename;user=username;password=password"
    statement => [ "exec dbo.procedure_name ?, ?, ?", "host", "@timestamp", "message" ]
}
```

If you can try it out and let me know if it works, that would be great.

If it doesn't work do let me know, and I'll power up a test machine to try a few things out. Probably won't be until later in the weekend though.

**Comment by starlessboi** [comment]
sorry for delay
I followed your sample. it's working
Thanks for your time

**Comment by theangryangel** [comment]
Thanks @starlessboi - much appreciated 👍

**Comment by Fl4g** [comment]
Hi guys,
could you please post your stored procedure used in this example?
Thanks a lot

**Comment by theangryangel** [comment]
It was just a test procedure that inserted some data into a table. It probably wasn't anything fancier than the following... (bear in mind I've written this as T-SQL. The syntax for your database may be different...)
```
CREATE PROCEDURE dbo.procedure_name @hostname varchar(512), @timestamp datetime, @message varchar(max)
AS  
  insert into dbo.log (hostname, timestamp, message) values(@hostname, @timestamp, @message)
GO  
```

**Comment by theangryangel** [comment]
Logstash does not permit output plugins to return new data. If you want to do something with the data returned from an output plugin you're gonna have to write a custom plugin. If you're mistaking this for the jdbc input plugin, this is completely unrelated and you need to raise it at https://github.com/logstash-plugins/logstash-input-jdbc
