### ISSUE TITLE
Failed to flush outgoing items

### ISSUE THREAD

**Issue by icemouton** [theangryangel/logstash-output-jdbc#44]
## Expected & Actual Behavior
I've been seeing this error pop up in my logstash logs ever since I updated the plugin to 0.2.7
Usually eerything works fine and then after a while I get these errors repeatedly in the logs, and my outputs (jdbc and elasticsearch) stop getting new logs...
Restarting logstash usually fixes the problem, but it keeps reoccuring.

Using mysql-connector-java-5.1.38-bin.jar with logstash-output-jdbc-0.2.7
Logstash version 2.1.1

{:timestamp=>"2016-06-28T16:45:11.285000-0400", :message=>"Failed to flush outgoing items", :outgoing_count=>307, :exception=>"NameError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.7/lib/logstash/outputs/jdbc.rb:337:in `retry_exception?'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.7/lib/logstash/outputs/jdbc.rb:246:in `safe_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.7/lib/logstash/outputs/jdbc.rb:243:in `safe_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.7/lib/logstash/outputs/jdbc.rb:230:in `safe_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.7/lib/logstash/outputs/jdbc.rb:143:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

**Comment by theangryangel** [comment]
I've pushed 0.2.8 to rubygems. Can you try updating and seeing if that resolves the problem please?

I have the feeling this is masking the real problem, unfortunately.

**Comment by theangryangel** [comment]
If you're still getting this problem with 0.2.10 or 0.3.0 please let me know. I believe it's now resolved.
