### ISSUE TITLE
Exception when insert

### ISSUE THREAD

**Issue by longjq** [theangryangel/logstash-output-jdbc#45]
i hava a table，fields has id,name,type。
so，when I insert row，program hava Exception ，
you can try~~~

**Comment by theangryangel** [comment]
You need to give me more information about what the exception is. 

I can't fix a problem when I don't know what the problem is.

**Comment by longjq** [comment]
`Logstash version`
 2.3.3

`Plugin version`
logstash-output-jdbc (0.2.7)

`Exception message`
```
//input data = {"id"=>33,"name"=>"jack","type"=>"big"}

output {
    jdbc {
          ....
          ...
          statement => [ "insert into tb_name(`id`,`name`,`type`) values(?,?,?)", "id","name","type" ]
   }
}
```
Can`t Insert，Logstash problem looks like a new version of the `type` caused by keywords

`JDBC driver`
mysql-connector-java-5.1.36-bin.jar

**Comment by theangryangel** [comment]
I've just spun up a virtual machine and had no problem. I'm using MySQL 5.5.49, JDBC 5.1.36, and the same version of the plugin and Logstash as you. 

Can you give me the text from the log when an exception happens. It should say something like:
```
JDBC Exception encountered: Will automatically retry. {:exception=> ....
```

I need the full line please.

**Comment by theangryangel** [comment]
If you're still getting this problem with 0.2.10 or 0.3.0 please let me know. I believe it's now resolved.

**Comment by longjq** [comment]
i'm sorry, Is I made a mistake, the program running success  ~~
