### ISSUE TITLE
JDBC Exception. No retry. {:exception=>#<NoMethodError: undefined method `start_with?' for 1:Fixnum>, :level=>:error}

### ISSUE THREAD

**Issue by alexschultz** [theangryangel/logstash-output-jdbc#46]
## Expected & Actual Behavior
Exception message 
JDBC Exception. No retry. {:exception=>#<NoMethodError: undefined method `start_with?' for 1:Fixnum>, :level=>:error}
Failed to flush outgoing items {:outgoing_count=>1, :exception=>"NoMethodError", :backtrace=>["C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.9/lib/logstash/outputs/jdbc.rb:332:in `log_jdbc_exception'", "org/jruby/RubyKernel.java:1479:in `loop'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.9/lib/logstash/outputs/jdbc.rb:326:in `log_jdbc_exception'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.9/lib/logstash/outputs/jdbc.rb:339:in `retry_exception?'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.9/lib/logstash/outputs/jdbc.rb:244:in `safe_flush'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.2.9/lib/logstash/outputs/jdbc.rb:143:in `flush'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in `loop'", "C:/Program Files/elastic/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
## Your Environment
Logstash version 2.3.3
Plugin version 0.2.9
JDBC driver Sql Server JDBC Driver
https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774

**Comment by theangryangel** [comment]
Can you give me the config you're running, if possible please Alex?

**Comment by alexschultz** [comment]
input {
	couchdb_changes {
	    db => "couchDocumentDb"
	    host => "localhost"
	    username => "admin"
	    password => "password"
	}
}

filter {
}

output {
	if [doc][schema] == "special" {
		jdbc {
			idle_flush_time => 10
			flush_size => 5
			max_flush_exceptions => 5
			username => "user"
			password => "password"
			connection_string => "jdbc:sqlserver://localhost:1433;databaseName=helloworld;"
		    statement => [ "INSERT INTO dbo.reports (ReportServer, ReportName, ReportPath, IsActive, CreatedBy, CreateDate, LastModifiedDate, IsAddParameter) VALUES(?, ?, ?, ?, ?, ?, ?, ?)", 
		    "%{[doc][schema]}",
		    "%{[doc][schema]}",
		    "%{[doc][schema]}",
		    1,
		    "%{[doc][schema]}",
		    "%{[doc][schema]}",
		    "%{[doc][schema]}",
		    "%{[doc][schema]}",
		    1]
			}
		}
	}

**Comment by theangryangel** [comment]
Just to see what happens, can you add quotes around the ``1``'s in the statement array? I'm going to guess that it works. If that's the case I think I have a quick patch to write 😅

**Comment by alexschultz** [comment]
Awesome, that fixed the initial issue! I have a couple of SQL syntax issues but I think those might be on my end. 
Thanks for the super quick reply!

**Comment by theangryangel** [comment]
Thanks for being responsive! (seriously :heart:)

Honestly, it really shouldn't be error'ing like that, so I definitely have a patch to write and some test cases to add 👍 

The SQL statement does have a mismatched number of ``?``'s and columns, so there is that as well.

**Comment by theangryangel** [comment]
I've backported this fix from the v5 branch to for v2 of logstash, and pushed 0.2.10 to rubygems 😄 

You should find that this now works correctly, without throwing any errors

**Comment by alexschultz** [comment]
It's working now, thanks for the super quick turnaround!
