### ISSUE TITLE
Blank rows are getting inserted when i call different table than "log"

### ISSUE THREAD

**Issue by me-vineet** [theangryangel/logstash-output-jdbc#50]
Blank rows are getting inserted when i call different table than "log"

## Expected & Actual Behavior
I am picking up data through logstash & insert it into postgres DB

input {
    stdin { }
    }
output {
    jdbc {
    	driver_jar_path => 'D:\OpenSource\postgres\postgresql-9.4.1208.jre6.jar'
        connection_string => 'jdbc:postgresql://localhost:5432/loglog?user=postgres&password=password'
        statement => [ "INSERT INTO ping (action, url, description) VALUES(?, ?, ?)", "action", "url", "description" ]
    }
}

although i see number of rows getting increased each time i provide input through stdin, i do not see data?

Plz help!

## Your Environment
* Version of plugin used: logstash-output-jdbc-2.x(Windows7)
* Version of Logstash used:  logstash-2.3.3(Windows7)
* Database engine & version you're connecting to: postgresql-9.5.3-1-windows-x64
* Have you checked you've met the Logstash requirements for Java versions?: YES

**Comment by theangryangel** [comment]
In the example config any data you insert using stdin will be in the event field "message" (that's just how logstash's stdin works).

In your jdbc output you don't have the field message, so it's inserting blank data, as there's no data in the fields you're inserting!

If you swap one of the fields in the jdbc statement with message you should see what I mean.

Alternatively you could use the kv filter and input your message into stdin in the format that kv expects.. 

Does that make sense?

**Comment by me-vineet** [comment]
it makes lots of sense Karl & I am also able to validate it by making adjustment into my table structure
Thank you for clarifying it!
![capture](https://cloud.githubusercontent.com/assets/17965187/16802939/f1b2501e-4920-11e6-96b3-8f110e34f88f.PNG)

couple of queries:
1. I see that Host, timestamp, message are hardcoded into the SQL call(Yes?)
2. Idea is to be able to pull system performance data (via beats/logstash) & post it to a postgres table(not able to figure out how can i do it using this plugin?)

Thanks for your help!

**Comment by theangryangel** [comment]
I think you need to go and re-read the Logstash documentation. I'll give you some information, but at this point you're asking very basic questions about how to configuration Logstash, not with this plugin.

host and @timestamp are set by Logstash, not this plugin.
The stdin input sets the field message. Different inputs set different fields.

Take a look at http://imgur.com/wqJHjTk which shows me configuring topbeat with logstash to output to stdout. Near the end of the video (about 1 minute in) I show that it has completely different fields than stdin does.

**Comment by me-vineet** [comment]
you are right, i got bit confused with the hard coded values(timestamp, host etc.) & was assuming that there is a mapping of fields to be mentioned in the conf file while making connection

I am using now able to input data into my tables by altering the input filter(as suggested by you) & it works perfectly fine!

Thanks a ton for your help ANGRY"ANGEL" :8ball: 
![capture](https://cloud.githubusercontent.com/assets/17965187/16805787/77530430-492f-11e6-9ea2-99418a7d9ea9.PNG)
