### ISSUE TITLE
statement sql

### ISSUE THREAD

**Issue by longjq** [theangryangel/logstash-output-jdbc#54]
```
jdbc {
			driver_jar_path => "E:/www/analyze/doc/mysql-connector-java-5.1.36-bin.jar"
			driver_class => "com.mysql.jdbc.Driver"
			connection_string => "jdbc:mysql://127.0.0.1/demo?user=root&password=root"		
			statement => [ "INSERT INTO `user_events_log_2016_08`(user_id,event,time,name,package,version,created_at,updated_at) values(?,?,?,?,?,?,?,?)","%{[@fields][ctxt_user_id]}","%{[@fields][ctxt_event]}","%{[@fields][ctxt_time]}","%{[@fields][ctxt_name]}","%{[@fields][ctxt_package]}","%{[@fields][ctxt_version]}","%{[@fields][ctxt_created_at]}","%{[@fields][ctxt_updated_at]}" ]
		}

```
the table name will be change~

example：
today is `2016-08-24`
so, table name need change to 
INSERT INTO user_events_log_`2016_08_24`(user_id,event,time,name,package,version,created_at,updated_at) values(?,?,?,?,?,?,?,?)

How to use???

Thank you for you help!

**Comment by theangryangel** [comment]
You need to set ```unsafe_statement = true``` option and dynamically set the table name.

The example from the documentation should get you started:
```[ "insert into %{table_name_field} (column) values(?)", "fieldname" ]```

**Comment by longjq** [comment]
think you !!!
