### ISSUE TITLE
phoenix-thin-client JDBC doesn't work

### ISSUE THREAD

**Issue by syshin0908** [theangryangel/logstash-output-jdbc#60]
I'm trying to upset to phoenix query server with phoenix-thin-client.
But it doen't work with bellow error message.

Pipeline aborted due to error {:exception=>com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 10000ms., :backtrace=>["com.zaxxer.hikari.pool.HikariPool.initializeConnections(com/zaxxer/hikari/pool/HikariPool.java:535)", "com.zaxxer.hikari.pool.HikariPool.<init>(com/zaxxer/hikari/pool/HikariPool.java:137)", "com.zaxxer.hikari.HikariDataSource.getConnection(com/zaxxer/hikari/HikariDataSource.java:94)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)", "RUBY.setup_and_test_pool!(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.3.0-java/lib/logstash/outputs/jdbc.rb:152)", "RUBY.register(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.3.0-java/lib/logstash/outputs/jdbc.rb:113)", "RUBY.register(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:75)", "RUBY.start_workers(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.start_workers(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181)", "RUBY.run(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136)", "RUBY.start_pipeline(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473)", "java.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:error}

phoenix-thick-client is working very well.

my config is :
output {
    jdbc {
        driver_class => "org.apache.phoenix.queryserver.client.Driver"
        connection_string=> "jdbc:phoenix:thin:url=http://localhost:8765;serialization=PROTOBUF"
        statement => ["UPSERT INTO %{table_name} (v_time, hostname, cpu_avg) VALUES(?, ? , ?)", "v_time", "hostname", "cpu_avg"]
        unsafe_statement => true
    }
}

## Your Environment

- Version of plugin used: newest
- Version of Logstash used:  2.3.4
- Database engine & version you're connecting to: phoenix-queryserver 4.8
- Have you checked you've met the Logstash requirements for Java versions?:  OpenJDK 1.8.0_101

**Comment by theangryangel** [comment]
I don't have any experience with Phoenix myself, so forgive any silly questions, but - is this something I can setup quickly on a single node to test? Also if you run logstash with debug output, do you get any other information in the log file?

**Comment by syshin0908** [comment]
@theangryangel thanks for your reply.
For test, you should install hbase and phoenix and use query server. Because thin client is for query server, thick client can run stand-alone.

Install document is below.
https://phoenix.apache.org/Phoenix-in-15-minutes-or-less.html
https://phoenix.apache.org/server.html

and more log is :
Plugin not defined in namespace, checking for plugin file {:type=>"codec", :name=>"rubydebug", :path=>"logstash/codecs/rubydebug", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"76", :method=>"lookup"}
_discover_file: /home/mas/test/loggen/test.txt: new: /home/mas/test/loggen/test.txt (exclude is []) {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"310", :method=>"_discover_file"}
_discover_file: /home/mas/test/loggen/test.txt: skipping because it was last modified more than 86400.0 seconds ago {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"330", :method=>"_discover_file"}
config LogStash::Codecs::RubyDebug/@metadata = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::RubyDebug metadata=>false> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Stdout/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
Will start workers for output {:worker_count=>1, :class=>LogStash::Outputs::Stdout, :level=>:debug, :file=>"logstash/output_delegator.rb", :line=>"77", :method=>"register"}
config LogStash::Codecs::Plain/@charset = "UTF-8" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@driver_class = "org.apache.phoenix.queryserver.client.Driver" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@connection_string = "jdbc:phoenix:thin:url=http://bdsdevname01:8766;serialization=PROTOBUF" {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@statement = ["UPSERT INTO %{table_name} (v_time, hostname, cpu_avg) VALUES(?, ? , ?)", "v_time", "hostname", "cpu_avg"] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@unsafe_statement = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@codec = <LogStash::Codecs::Plain charset=>"UTF-8"> {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@workers = 1 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@driver_auto_commit = true {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@max_pool_size = 24 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@connection_timeout = 10000 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@flush_size = 1000 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@retry_initial_interval = 2 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@retry_max_interval = 128 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@retry_sql_states = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
config LogStash::Outputs::Jdbc/@max_flush_exceptions = 10 {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"153", :method=>"config_init"}
JDBC - Starting up {:level=>:info, :file=>"logstash/outputs/jdbc.rb", :line=>"96", :method=>"register"}
log4j java properties setup {:log4j_level=>"DEBUG", :level=>:debug, :file=>"logstash/logging.rb", :line=>"89", :method=>"setup_log4j"}
JDBC - jarpath {:path=>"/home/mas/test/logstash-2.3.4/vendor/jar/jdbc/*.jar", :level=>:debug, :file=>"logstash/outputs/jdbc.rb", :line=>"175", :method=>"load_jar_files!"}
JDBC - Loaded jar {:jar=>"/home/mas/test/logstash-2.3.4/vendor/jar/jdbc/phoenix-thin-client.jar", :level=>:debug, :file=>"logstash/outputs/jdbc.rb", :line=>"181", :method=>"load_jar_files!"}
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.3.0-java/vendor/jar-dependencies/runtime-jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/mas/test/logstash-2.3.4/vendor/jar/jdbc/phoenix-thin-client.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
_globbed_files: /home/mas/test/loggen/test.txt: glob is: ["/home/mas/test/loggen/test.txt"] {:level=>:debug, :file=>"filewatch/watch.rb", :line=>"346", :method=>"_globbed_files"}
Pipeline aborted due to error {:exception=>com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 10000ms., :backtrace=>["com.zaxxer.hikari.pool.HikariPool.initializeConnections(com/zaxxer/hikari/pool/HikariPool.java:535)", "com.zaxxer.hikari.pool.HikariPool.<init>(com/zaxxer/hikari/pool/HikariPool.java:137)", "com.zaxxer.hikari.HikariDataSource.getConnection(com/zaxxer/hikari/HikariDataSource.java:94)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)", "RUBY.setup_and_test_pool!(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.3.0-java/lib/logstash/outputs/jdbc.rb:152)", "RUBY.register(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-0.3.0-java/lib/logstash/outputs/jdbc.rb:113)", "RUBY.register(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:75)", "RUBY.start_workers(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.start_workers(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181)", "RUBY.run(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136)", "RUBY.start_pipeline(/home/mas/test/logstash-2.3.4/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473)", "java.lang.Thread.run(java/lang/Thread.java:745)"], :level=>:error, :file=>"logstash/agent.rb", :line=>"475", :method=>"start_pipeline"}
stopping pipeline {:id=>"main", :file=>"logstash/agent.rb", :line=>"388", :method=>"shutdown_pipelines"}
Closing inputs {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"384", :method=>"shutdown"}
stopping {:plugin=><LogStash::Inputs::File path=>["/home/mas/test/loggen/test.txt"], start_position=>"beginning", codec=><LogStash::Codecs::Plain charset=>"UTF-8">, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, delimiter=>"\n", ignore_older=>86400, close_older=>3600>, :level=>:debug, :file=>"logstash/inputs/base.rb", :line=>"81", :method=>"do_stop"}
Closed inputs {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"386", :method=>"shutdown"}

**Comment by theangryangel** [comment]
I'll see what I can figure out @syshin0908, although it's not going to be for a few days - sorry about that :( I'm very very busy at work this week and I literally have no free time outside of that at the moment

**Comment by theangryangel** [comment]
Phoenix is a 15 minute installation. As long as you have hbase. Which requires hadoop. And Zookeeper. Which in combination I know fuck all about, and it's not a technology I'm likely to use any anypoint in the near future. Combined with packages from Apache bigtop which overwrite each other I'm just struggling to motivate myself into learning just enough to get to the bottom of this. 

I'll be honest @syshin0908, I'm not sure this is how I want to spend my day off anymore.

So I'm going to go back to basics before I try and learn more than I absolutely need to about phoenix and hadoop.

Generally speaking if Hikari is throwing a connection error, that's exactly what it is. Are you able to get sqlline-thin.py to connect and issue queries? If not then there's absolutely no way the logstash plugin will work.

**Comment by syshin0908** [comment]
@theangryangel I'm sorry to bother you.
sqline-thin.py is working very well and java implementation is working also.
java code is below.

```java
@Test
public void queryServerTest() throws Exception {
    Connection conn;
    Statement stmt = null;
    Properties prop = new Properties();
    Class.forName("org.apache.phoenix.queryserver.client.Driver");
    conn = DriverManager.getConnection("jdbc:phoenix:thin:url=http://localhost:8765;serialization=PROTOBUF");

    ResultSet rst = conn.createStatement().executeQuery("select * from test");

    while (rst.next()) {
        System.out.println(rst.getString(1) + " " + rst.getString(2));
    }

    stmt.close();
    conn.close();
}
```

Your logstash plugin is working using org.apache.phoenix.PhoenixDriver(thick-client, ordinary JDBC) well.
Phoenix query server is implemented with Apache avatica. I think that this plugin can't be compatible with avarice.

**Comment by theangryangel** [comment]
I'll have another look at this in the next few days, hopefully I'll be less grumpy - sorry

**Comment by theangryangel** [comment]
@syshin0908 when you use sqlline.py how long does it take to connect normally? Longer than 10 seconds?

**Comment by syshin0908** [comment]
@theangryangel no. it takes just few seconds.

**Comment by theangryangel** [comment]
Sorry this one has taken so long @syshin0908. It's taken me a few months to get the will to look into this one.

For my reference, I've been testing this using:
 - hbase 1.2.4 standalone
 - phoenix 4.9.0 for hbase 1.2
 - phoenix-thin

It appears there were 2 issues:
1. The phoenix thin client does not bundle all it's requirements into the client jar
2. Phoenix thin client does not support isValid and Hikari never added anything to the pool

I've pushed logstash-output-jdbc 5.1.0 to rubygems with support to workaround these issues, with extra configuration options. You can checkout https://github.com/theangryangel/logstash-output-jdbc/blob/master/examples/apache-phoenix-thin-hbase-sql.md which shows what I was using to test

**Comment by syshin0908** [comment]
@theangryangel thanks a lot!!!!!!!!!!
