### ISSUE TITLE
a lot of connections to the DB

### ISSUE THREAD

**Issue by phr0gz** [theangryangel/logstash-output-jdbc#64]
Hello theangryangel,

I have a question about the plugin and the connections using MS SQL.
I've the version 0.2.10 of the plugin and logstash 2.4.0.

Is it normal that there are a lot (more than 50) of connections with the status "ESTABLISHED" to the MS SQL servers?

You can see all the connection status with: netstat -p | grep java

Thx

**Comment by theangryangel** [comment]
Upgrading to 0.3.0 or newer should reduce the number of connections significantly.

The reason why is before Logstash 2.2 you'd only get 1 instance of a plugin. [In 2.2 elastic.co changed this](https://www.elastic.co/blog/logstash-2-2-0-and-2-1-2-released), and how events get processed. The most important thing from that post is that unless you declare the plugin as threadsafe, you get multiple instances of the plugin. Unfortunately I wasn't aware of this change and only checked and declared the plugin threadsafe in 0.3.0 and newer.

This means with a plugin version <0.3.0 and Logstash>=2.2 the total possible number of connections that this plugin can open, would be number of pipelines * max_pool_size connections. This is why you're getting so many connections, and why upgrading should "fix" it 😄

**Comment by phr0gz** [comment]
omg, you reply too fast...and always with a solution! thanks, I will update the plugin!

**Comment by theangryangel** [comment]
Not a problem @phr0gz - if it helps you can also change the `max_pool_size` option to a lower number (i.e. 1) rather than upgrading.
