### ISSUE TITLE
Not compatible with logstash 2.4.0

### ISSUE THREAD

**Issue by s4nch3z** [theangryangel/logstash-output-jdbc#65]
YouWish:logstash-2.4.0 s4nch3z$ bin/logstash-plugin install logstash-output-jdbc
LogStash::GemfileError: duplicate gem logstash-filter-date
         add_gem at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/gemfile.rb:102
             gem at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/gemfile.rb:200
          (eval) at (eval):109
   instance_eval at org/jruby/RubyBasicObject.java:1598
           parse at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/gemfile.rb:188
            load at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/gemfile.rb:19
         gemfile at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/command.rb:4
  verify_remote! at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/install.rb:50
         execute at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/install.rb:28
             run at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
         execute at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
             run at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
             run at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
          (root) at /Users/s4nch3z/dev_platform/solidopinion.com/logs/logstash-2.4.0/lib/pluginmanager/main.rb:43

**Comment by theangryangel** [comment]
Sorry but this is not a bug with the plugin, but a bug in the released version of Logstash 2.4.0 - please see https://github.com/elastic/logstash/issues/5852 where the Logstash project provide a workaround.
