### ISSUE TITLE
Fix Documentation for @timestamp vs %{@timestamp} (was: strange error and debug info for the plugin?)

### ISSUE THREAD

**Issue by iti888** [theangryangel/logstash-output-jdbc#70]
I am using 5.1.1 ELK stack and using output_jdbc plugin to update Oracle 12c about the status of the ETL.
I have a strange error:
I have 10 Oracle inputs (input_jdbc plugin) and 1 output to the same Oracle server. The output updates 10 records in the status table. But if I use only 1 output, not all 10 records get updated. (I have outputs to ES and were all successful). Strange thing is that if I single out those not updated one and setup another output for it and it is successful.
Input{
jdbc 1{}
..
jdbc 10 {}
}
Output
{
if done {  -- condition when 1 input finishes
jdbc 1{}
}
}
This config fail for some say 4, 8,9,10
This config works:
input{
jdbc 1{}
..
jdbc 10 {}
}
Output
{
if done {
if [type] =~ "^?[4,8,9,0]{1}$" { --pick out those having problem and handle it separately
jdbc 1{}
} else {
jdbc 2 {}
}
}
}
How can this be happening? 1 and 2 are identical. Any setting that I need to add? (ojdbc6.jar or odjbc7.jar behave the same)  to make the first config works?

BTW, the plugin does not have any debug/info output. Like the SQL statement etc. Can this be added?
Thanks

**Comment by theangryangel** [comment]
I can't think of a reason why this would happen off the top of my head.. I'd guess either the plugin is retrying and failing - but it should eventually log that it failed after however many attempts you've configured it for (10 by default).

Is there any possibility you can run the problem configuration with the logstash `--debug` flag, and try and make the problem happen? That should put logstash-output-jdbc and HikariCP (a component the plugin uses) into a very spammy mode, and should give you some SQL errors. If you can copy the log into here, it would be very very helpful.

With regards to the debug info for the sql statement, the plugin runs a prepared statement of what you give it (unless you're using the `unsafe_statement` option, I suppose), meaning it would just output whats in the config, the event. I usually just use `stdout { codec => rubydebug }` if I absolutely have to.

**Comment by iti888** [comment]
I did turn on the debug and did not see any error.(Plugin did not show SQL, so I do not know if it got executed, I just know ES output got there.  That is why I want to you add SQL before execution as INFO so that I will know if the SQL got executed or not.)
I did not use unsafe-statement option.
Here is the entire log from start to shutdown, running 10(+2 start and stop) and 1 output(+1 concluding output). Updating 2 tabes. Table 2 is status table:(Result is append to the end of the log)
Notice that 4,8,9,10 status is still "P" but everything is completed. If I single them out with another output, then they will be all "C". Strange.

[logstash-plain.txt](https://github.com/theangryangel/logstash-output-jdbc/files/705250/logstash-plain.txt)

**Comment by iti888** [comment]
@theangryangel 
The problem is because I am using aggregate filter and tried to detect the 1st and last record. When there is only one aggregate. My output detect it as 1st record and change the status to "P", but it also is the last record and tried to set it to "C". This caused conflict I guess. (But there are 2 jdbc outputs, one for 1st and one for last). Currently I detect 1st record using the original event and not the aggregate event and it works fine.
But the problem is still strange. Why there is such behavior? When I make a 3rd jdbc output for the last, it works fine also.
The output plugin seems to set the pool at full size and not incremental. Can this be changed? If I have 5 outputs, and the default pool size is 24. I am having 120 connections in the DB. Could this be set at say 2 and increment by say 4 till max?

One side question: How can I use Time.Now.strfmt(....) as Statemtment parameter?
statement =>["select * from tab where date=?",Time.now.strfmt(...)] 
This syntax is ok with the config, but not work when executing in the plugin.

**Comment by theangryangel** [comment]
I'm sorry @iti888, but I've just not had the time yet to think about this problem, let alone try and actually figure it out.

> But the problem is still strange. Why there is such behavior? When I make a 3rd jdbc output for the last, it works fine also.

I honestly don't really understand exactly what you're trying to do. Can you give me the exact, or very close configuration... I have the feeling this is more of a configuration error than a plugin problem.

> One side question: How can I use Time.Now.strfmt(....) as Statemtment parameter?

You can't... Logstash doesn't execute the configuration as if it's ruby (except for one plugin). I'd personally suggest using something like `CURRENT_TIMESTAMP`, or `sys_extract_utc(SYSTIMESTAMP)` in your sql. i.e. `statement =>["select * from tab where date=sys_extract_utc(SYSTIMESTAMP)"]`

If you **absolutely** have to use Time.Now.strfmt, then your only option is to use the [ruby filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html) to add a field to the event. Something like this might work (i've not tested this):
`ruby { code => "event.set("new_timestamp", Time.Now.strfmt(...)" }`

**Comment by iti888** [comment]
I tested again. It is scheduling/timing problem. There are 2 job trying to update the same record, but they are different connections, which caused the issue. 
As for Time.Now.strfmt(....), I just figured out how to do it without adding a field. It is strange howthe plugin treated the Statement parameter:
UPDATE table  ts_field=to_timestamp(?,'yyyy-mm-dd HH24:MI:SS.ff3') will work with parameter "@timestamp" but not "%{@timestamp}".
"%{@timestamp}" has a format  'yyyy-mm-dd"T"HH24:MI:SS.ff3"Z"'
while "@timestamp" has a format of 'yyyy-mm-dd HH24:MI:SS.ff3'
also ["UPDATE table  ts_field=to_timestamp(?,'yyyy-mm-dd\"T\"HH24:MI:SS.ff3\"Z\"')...", "%{@timestamp}"] does not cause config or runtime error.
But from Oracle DB side. The Escape "\" was in the formating string. So, it failed. How do you make this to work?

**Comment by theangryangel** [comment]
Welcome to the wonderful world of logstash.

https://logstash.jira.com/browse/LOGSTASH-1377 has been open since 2013 about quoting problems in configurations.

The problem is that JDBC drivers have given us issues in the past for timestamps, as drivers all seem to work differently for setting timestamps. 

According to https://github.com/theangryangel/logstash-output-jdbc/blob/master/examples/oracle.md josemazo had success using `CAST(? as timestamp)`, with `@timestamp`.

I'm afraid I don't use Oracle and I'm not going to have time to install and investigate myself for a while.

**Comment by iti888** [comment]
Looks like I just cannot use \" to escape double quote. (but Oracle time formatting needs that:) )
As for @timestamp. My confusion is why "@timestamp" and "%{@timestamp}" is different. Isn't one is the field itself and the other is string of the field? How does the plugin passing the parameter to the SQL? (Convert to string and pass or JDBC is doing the conversion?)

**Comment by theangryangel** [comment]
When you use `@timestamp` the plugin converts it to a string. The reason is explained in https://github.com/theangryangel/logstash-output-jdbc/blob/master/lib/logstash/outputs/jdbc.rb#L277 - but basically some JDBC drivers correctly support setTimestamp whereas others dont.

The reason why `%{@timestamp}` is different is because that `%{}` is logstash itself converting the timestamp to a string, and using a slightly different format. The reason why I use a different formatting string is because a different SQL engine failed to support logstash's format.

Ways forward at this point:
1. I can add a configuration parameter that governs the format that the string gets converted to, allowing you to configure it differently
2. I can add a configuration parameter that tells the plugin to use setTimestamp instead of setString

**Comment by iti888** [comment]
I was just wondering the inconsistency of formatting. As long as there is somekind of documentation saying the @timestamp parameter is treating differently as "@timestamp" or "%{@timestamp}". That is enough. I have to go a long way to find this out. (Because I can not use double quote. I have to convert the Time.now using strfmt(..) to a new field in the EVENT and pass as a parameter. Then I found "@timestamp" works exactly the same as what I was formatting.)
