### ISSUE TITLE
Logstash v2 downloading v5? (Was: Installation for logstash 2.x)

### ISSUE THREAD

**Issue by jonathortense** [theangryangel/logstash-output-jdbc#71]
I'm trying to install this plugin for logstash 2.4

When I run: `bin/logstash-plugin install logstash-output-jdbc`, it  seems that it is installing from branch master.
And I receive this error:

```
{:timestamp=>"2017-01-19T11:03:46.939000+0000", :message=>"Pipeline aborted due to error", :exception=>"NoMethodError", :error=>"undefined method `trace' for #<Cabin::Channel:0x1c1f9523>", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-5.1.0-java/lib/logstash/outputs/jdbc.rb:184:in `load_jar_files!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-jdbc-5.1.0-java/lib/logstash/outputs/jdbc.rb:105:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}
{:timestamp=>"2017-01-19T11:03:49.927000+0000", :message=>"stopping pipeline", :id=>"main"}
```

How can I install this plugin using branch v2.x?

Thank you.

**Comment by theangryangel** [comment]
Erm... Thanks for letting me know... I don't see why that would be unless I've really fucked something up. I'll try and find the time to figure out why thats happened later...

Best suggestion I've got is to download the gem from `https://rubygems.org/downloads/logstash-output-jdbc-0.3.2-java.gem`, and then run `bin/logstash-plugin install path/to/logstash-output-jdbc-0.3.2-java.gem`. Pretty sure that still works, but I've not tried it for a long time.

**Comment by jonathortense** [comment]
Wow.. thanks for the quick reply. 
I worked around this problem with: `logstash-plugin install --version 0.3.2 logstash-output-jdbc`

It also works!

Thank you.

**Comment by theangryangel** [comment]
Sorry it was broken in the first place, but thank you very very much for reporting it! 👍
