### ISSUE TITLE
Problems installing logstash-output-jdbc

### ISSUE THREAD

**Issue by elMor3no** [theangryangel/logstash-output-jdbc#73]
im trying install the pluging but every time i get this error

root@squid:/opt/logstash/bin# ./logstash-plugin install logstash-output-jdbc-master/
Validating logstash-output-jdbc-master/
Plugin logstash-output-jdbc-master/ does not exist
ERROR: Installation aborted, verification failed for logstash-output-jdbc-master/

**Comment by theangryangel** [comment]
The command is `logstash-plugin install logstash-output-jdbc` - no master required.

**Comment by elMor3no** [comment]
Thx.... Works...

**Comment by elMor3no** [comment]
where i found the jar files to continue with the installation process?

>>>
Now either:

    Use driver_jar_path in your configuraton to specify a path to your jar file

Or:

    Create the directory vendor/jar/jdbc in your logstash installation (mkdir -p vendor/jar/jdbc/)
    Add JDBC jar files to vendor/jar/jdbc in your logstash installation
