### ISSUE TITLE
Installation process...

### ISSUE THREAD

**Issue by elMor3no** [theangryangel/logstash-output-jdbc#74]
**where i found the jar files to continue with the installation process?

Now either:

Use driver_jar_path in your configuraton to specify a path to your jar file

Or:

Create the directory vendor/jar/jdbc in your logstash installation (mkdir -p vendor/jar/jdbc/)
Add JDBC jar files to vendor/jar/jdbc in your logstash installation
**

**Comment by theangryangel** [comment]
It depends what sql engine you're connecting to....? This plugin should in theory support anything that has a JDBC driver. Most JDBC drivers are available on the sql engine's website.

Many of the examples in https://github.com/theangryangel/logstash-output-jdbc/tree/master/examples list where the JDBC driver can be found.

I don't want to be a dick, but if you don't understand what a JDBC driver is and where to find them, I think you're going to struggle configuring the plugin...

**Comment by elMor3no** [comment]
Unffortunably i live in Cuba and is imposible to me download from there https://dev.mysql.com/downloads/file/?id=457911

always i get 
https://www.mysql.com/downloads/embargo.html
Thank you for your interest in MySQL.

In compliance with U.S. and applicable Export laws we are unable to process your request.  Please contact RPLS-Ops_ww@oracle.com if you believe you are receiving this notice in error.

**Comment by theangryangel** [comment]
Try maven - http://mvnrepository.com/artifact/mysql/mysql-connector-java

**Comment by elMor3no** [comment]
Thanks.... sorry for my stupid questions... first time working with jdbc

**Comment by theangryangel** [comment]
It's ok. I'm sorry I'm a bit grumpy this evening :) If you need anything else, reopen the issue and I'll do what I can to help.
