### ISSUE TITLE
Does this plugin support if statement？

### ISSUE THREAD

**Issue by ttssrs** [theangryangel/logstash-output-jdbc#76]
Hi ,

When I using this plugin to insert some fileds into my database, I write the output like this:
jdbc{
    driver_jar_path => "mysql-connector-java-5.1.41-bin.jar"
   driver_class => "com.mysql.jdbc.Driver"
   connection_string => "jdbc:mysql://..."
   if("60001" in [tags]){
       statement => ["insert into logTable values(?,?,?)","ID","Code","Name"]
   }
   else{
       statement => ["insert into logTable values(?,?,?),(?,?,?)","ID","Code","Name","ID","DepartID","DepartName"]
   }

then I use "bin/logstash -f myconf.conf" to start logstash and get an error:
Cannot load an invalid configuration{:reason=>Expected one of # ... after if

thanks!

## Your Environment
* Version of plugin used: 5.1.41
* Version of Logstash used:  5.2.2
* Database engine & version you're connecting to: mysql
* Have you checked you've met the Logstash requirements for Java versions?: Yes

**Comment by theangryangel** [comment]
To my knowledge, no plugin supports this syntax, and it's unlikely I'll try and support it either.

However, logstash itself supports something very similar. You can achieve what you want by doing the following instead:

```
input { }
output {
  if("60001" in [tags]) {
    jdbc {
        driver_jar_path => "mysql-connector-java-5.1.41-bin.jar"
        driver_class => "com.mysql.jdbc.Driver"
        connection_string => "jdbc:mysql://..."
        statement => ["insert into logTable values(?,?,?)","ID","Code","Name"]
    }
  }
  else {
    jdbc {
        driver_jar_path => "mysql-connector-java-5.1.41-bin.jar"
        driver_class => "com.mysql.jdbc.Driver"
        connection_string => "jdbc:mysql://..."
        statement => ["insert into logTable values(?,?,?),(?,?,?)","ID","Code","Name","ID","DepartID","DepartName"]
    }
  }
}

```

**Comment by ttssrs** [comment]
Thanks for your replay.
