### ISSUE TITLE
Datatype Array not saving

### ISSUE THREAD

**Issue by Denakop** [theangryangel/logstash-output-jdbc#80]
Version of plugin used: 5.2.0
Version of Logstash used: 5.0.0-beta1
Database engine & version you're connecting to: Mariadb 10.1.22
Have you checked you've met the Logstash requirements for Java versions?: Yes

My datatype field array on elasticsearch is saving NULL in my database. 

On my database i'm using a TEXT type, so i expected to recive a json encoded param

**Comment by theangryangel** [comment]
Try using `%{fieldname}` as your parameter, rather than just `fieldname`. #77 has further details.

**Comment by gurodrigues** [comment]
Perfect !!

Now i'm using `%{fieldname}` but when this field does not existis on the elasticsearch document it instead of saving on database as `null` it save as `%{fieldname}`

An exemple of a database row
```
INSERT INTO `denakop` (`action`, `age`, `aid`, `browser`, `cid`, `city`, `country`, `cpm`, `date`, `device`, `dkUser`, `format`, `gender`, `host`, `ip`, `isp`, `os`, `path`, `pid`, `profiles`, `scheme`, `socialClass`, `state`, `status`, `subjects`, `userAgent`, `uxId`, `windowSize`)
VALUES
	('authorized', '%{age}', 0, 'chrome', 0, 'São Paulo', 'BR', 4.00, '24-01-2017 16:47:41', 'mobile', 'dkuser_5887a143df2876.36924690', '%{format}', '%{gender}', 'criticalhits.com.br', '200.161.232.125', 'Vivo', 'android', '/gta-6-chega-antes-no-brasil-e-consegue-proeza-de-modificar-o-alfabeto-romano/', 30, 'na', 'http', '%{socialClass}', 'São Paulo', '%{status}', '%{subjects}', 'Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4) Build/MPJ24.139-50) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36', 'uxid_5887a143df28e8.17171398', '360x640');
```

**Comment by theangryangel** [comment]
Unfortunately that's the draw back of using that syntax. It's specifically using the sprintf function on the logstash event, which acts like this if the event field is missing.

I've just pushed 5.2.1 to rubygems which contains a fix for using the alternative syntax (`fieldname`, rather than `%{fieldname}`). You'll need to upgrade, and then it should start returning JSON for Array and Hash objects.
