### ISSUE TITLE
UPSERT Functionality

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/logstash-output-jdbc#84]
> I've tested the plugin and seems to work, using simple statement query either for update or insert new data in the db, but what about if the database doesn't exist, or it exists but I want to update existing rows?

If you're actually trying to insert a row but want it to update an existing one if it already exists, then you want something commonly called upsert. Postgres supports this under 9.5 or newer using the insert on conflict syntax. https://hashrocket.com/blog/posts/upsert-records-with-postgresql-9-5 has a good example of how this can be used. If you're using an older version it should be a case of using an if exists then update else insert. You might want to make it a stored procedure for legibility.

If the actual database itself doesn't exist, you're probably out of luck. When the initial connection is made the database needs to exist. You might be able to workaround it, but I'm struggling to see the use case tbh.

**Comment by vktor18** [comment]
thanks for the reply @theangryangel 

Would you please give an example of how the `statement` field should look like using the upsert function?

thanks! :)

**Comment by vktor18** [comment]
I'm doing something like this:

```
statement => ["

        INSERT INTO userstate VALUES(?,?,?,?,?) on conflict (username)
        do update set (business_name, iban, status, timestamp) = ('%{[resource][response_attributes][business_name]}','%{[resource][response_attributes][iban]}','%{[resource][response_attributes][status]}','%{@timestamp}')
        where userstate.username = '%{[request][username]}';", "%{[request][username]}","%{[resource][response_attributes][business_name]}","%{[resource][response_attributes][iban]}","%{[resource][response_attributes][status]}","%{@timestamp}"
        ]
```
but the update is not working...the insert works fine. Am I doing something wrong?
