### ISSUE TITLE
postgres as NOSQL 

### ISSUE THREAD

**Issue by vktor18** [theangryangel/logstash-output-jdbc#85]
I don't think this output plugin supports the usage of postgres as NOSQL, which is a feature it has.

If I'm wrong, have somebody used this plugin in nosql mode?
thank you

**Comment by theangryangel** [comment]
You can insert into JSON or JSONB using this plugin. I do exactly this at work. HSTORE, probably isn't going to be a thing for now.

The only caveat is that there's currently no way to insert the whole raw event as JSON. There is an open PR (#83) which has not yet been merged due to concerns with the suggested syntax.

**Comment by vktor18** [comment]
Do you mean the whole logstash event?

Would you please show me how do you insert using this plugin? I know how to do it from the postgres shell but I failed with the plugin :D

**Comment by theangryangel** [comment]
Sorry for the delay @vktor18.

Currently I have events that look like this:
```
{
  "computer_name": "blashads",
  "@timestamp": "2017-01-01T15:15",
  "event_id": 12123,
  "event_data": { "something":  "awesome", "something else": "great" }
}
```

And I insert the `event_data` into Postgres as JSON using the following:

```
output {
	jdbc {
		driver_jar_path => 'postgresql-42.0.0.jar'
		
  		connection_string => 'jdbc:postgresql://my_servername:5432/my_database?user=my_username&password=my_password'
		statement => [ 'insert into my_table_name (computer_name, event_timestamp, event_id, event_data) values(?, CAST(? as timestamp), ?, CAST(? as json))', "computer_name", "@timestamp", "event_id", "%{event_data}" ]
	}

}
```

Bear in mind that doesn't submit the whole event. Just 1 part of it. The whole thing still depends on a patch which I've not gotten around to looking at properly.

**Comment by vktor18** [comment]
Thank you @theangryangel for the reply!
