### ISSUE TITLE
How to define multiple INSERT INTO statements

### ISSUE THREAD

**Issue by Fl4g** [theangryangel/logstash-output-jdbc#90]
Hi, 
I have a question:
I'm using the following statement to parse data from a JSON file into my database:
`statement => [ "INSERT INTO db_name.table_name (value, timestamp, name) VALUES (?, ?, 'spezific_name')","%{[value][data][spezific_name]}","timestamp" ]`

Now i need to do this for more than one spezific_name. Can you tell me how to do this?
I tried using a second statement like this:
`statement => [ "INSERT INTO db_name.table_name (value, timestamp, name) VALUES (?, ?, 'spezific_name')","%{[value][data][spezific_name]}","timestamp" DELIMITER  
 "INSERT INTO db_name.table_name (value, timestamp, name) VALUES (?, ?, 'spezific_name2')","%{[value][data][spezific_name2]}","timestamp" ]`
but I don't know the correct delimiter and keep getting an error.

Thanks

**Comment by theangryangel** [comment]
The first parameter is always the statement, the following are always the parameters. 

The only way you'll get multiple statements is;
1. If whatever DB you're using supports the syntax `INSERT INTO table_name VALUES(?, ?), (?, ?)`, and you're inserting both rows into the same table - most DBs I've used support this syntax
2. If whatever DB you're using supports multiple insert statements in the same prepared statement (many don't - infact I believe only MySQL supports it with allowMultiQueries=true) - if you happen to be using MySQL something like `INSERT INTO table_name VALUES(?, ?); INSERT INTO table_name VALUES(?, ?)` might work
3. Using a stored procedure instead
4. Patching the plugin (PRs are welcome)

**Comment by Fl4g** [comment]
Thanks for the answer. I am using MySQL by the way.
1. Suggestion: I tried the first suggestion like this:
`statement => [ "INSERT INTO db.table (value, timestamp, name) VALUES (?, ?, 'name1'), (?, ?, 'name2')", "%{[value][data][name1]}", "timestamp", "%{[value][data][name2]}", "timestamp" ]`
I keep getting the error message : "{:exception=>java.sql.SQLException: Data truncated for column 'value' at row 2}"
2. Suggestion: Already tried that with added "AllowMultiQueries=true" to the connection string. Not working as well.
3. Suggestion: I've never used a procedure before and am a little frightened ;)

Please excuse my bad english, but it's not my native tongue. :D
