### ISSUE TITLE
Logstash v6 support

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/logstash-output-jdbc#91]
Need to check if there are any compatibility issues or changes.

**Comment by phr0gz** [comment]
Hello, did you check if it is working? Or should I try and provide you a feedback?

**Comment by theangryangel** [comment]
I've not had any time to investigate yet. I saw it went GA yesterday, and I was hoping to make some time today or tomorrow :( The documentation suggests it should work with no changes, but I've read that before :D If you have time and want to check it out, please go ahead!

**Comment by phr0gz** [comment]
FYI: I will be able to test it tomorrow, I already installed the plugin without any issue. I still need to setup the windows SQL server, and to install the jdbc driver on the logstash box.

**Comment by jksecurity** [comment]
I have just tested the plugin on LS6. I pulled over 2 million events from ES and imported them into MariaDB without any issues whatsoever.

Keep up the great work!

**Comment by LucaWintergerst** [comment]
I'm also using this with LS 6.0.0 and so far things work without any issues

**Comment by theangryangel** [comment]
Thanks for the feedback guys, really appreciate you guys testing it out and coming back to the repo to let us know :+1:

**Comment by phr0gz** [comment]
Sorry for being late (and re-open the 'issue'), selinux was driving me mad. It's working well with MS SQL 2017 (windows version).
