### ISSUE TITLE
JDBC Driver connection pool szie

### ISSUE THREAD

**Issue by joginar10** [theangryangel/logstash-output-jdbc#92]
I'm using jdbc driver to transfer data to postgresql.
I encountered **Too Many Connections** error when i run multiple jdbc output instance.
There are 11 output instances and it should only have 55 jdbc instance in postgre.
When I checked the pgadmin, there are 181 connections from JDBC Driver.
How come JDBC exceeds in number of connections?

**Comment by theangryangel** [comment]
What version of the plugin and what version of logstash are you using? Whats your configuration set to max? Older versions had an issue relating with too many connections, and I believe it has since been fixed.

**Comment by theangryangel** [comment]
Hi @joginar10 did you upgrade? Are you able to provide any more information?

**Comment by joginar10** [comment]
Hi @theangryangel ! I did not upgrade the jdbc driver. I fixed the problem when I figured out that there's some mistakes in my config. It works fine after all. Thank you very much! :dagger:
