### ISSUE TITLE
single retry connection

### ISSUE THREAD

**Issue by mlkmhd** [theangryangel/logstash-output-jdbc#93]
Hi,

I'm using this plugin for import huge amount of wildfly server logs to oracle db. when the database down (for one or two hour) and the server logs are producing continually. this is my output config:

    output {

        connection_string => "sampleOracle..."

        retry_initial_interval => 2

        retry_max_interval => 10

        statement => "INSERT into ..."

    }

the logstash produces many error log (sql connection exception) in output console and it uses very cpu cycle for retrying. I think this happen because the logstash input generate many logs and the output can't control concurrency for single retry connection!

Is there any relation between logstash output plugin and input plugin that output stop the input producing until a period of time? for example if the connection interrupted then the output plugin tell the input plugin to stop reading files for a while?

## My Environment
* Version of plugin used: Latest
* Version of Logstash used:  5.2
* Database engine & version you're connecting to: Oracle 11g
* Have you checked you've met the Logstash requirements for Java versions?: yes

**Comment by theangryangel** [comment]
Older versions of the plugin do suffer from performance issues with retrying. However, the plugin is not designed for the database to be down for extended periods of time. If you’re not on a recent version of the plugin and logstash I would try upgrading to see if it helps (might not).

If you’re already on a more recent version of the plugin you can adjust the retry timers with the configuration options. This might help a little, however it really depends on your load.

There is no method (that I am aware of) for an output plugin to tell an input to stop ingesting data. 

If you have a large volume of events you’re running through and have the database disappearing for hours at a time I would suggest finding another solution. Logstash isn’t really a good fit here. It sounds like you’re trying to use it as some kind of ETL tool?

If you want to continue using logstash with this plugin you’ll need to patch it to deal with this scenario as you see fit - either dropping events or significantly altering the retry functionality.

Without more information on the volume of events, your configuration, logstash and plugin versions i cannot suggest more. But having your log storage (sql server) disappearing is really not ideal.
