### ISSUE TITLE
log sql exceptions in more detail

### ISSUE THREAD

**Issue by mlkmhd** [theangryangel/logstash-output-jdbc#94]
Hi,

I have an exception in insert to db like this:
`JDBC - Exception. Not retrying. {:exception=> java.sql.SQLIntegerity....}`
the above log only include the exception that produced by db. Is it possible to log the sql insert query that caused the problem?

thanks

## My Environment
* Version of plugin used: latest
* Version of Logstash used:  5.6.0
* Database engine & version you're connecting to: Oracle 11g
* Have you checked you've met the Logstash requirements for Java versions?: yes

**Comment by theangryangel** [comment]
Patch merged. Tests failed due to logstash changes. Will test manually and cut release when I have a moment.

Thank you for your patch. Are you happy if I add you to the THANKS file?
