### ISSUE TITLE
jdbc output with jdbc input

### ISSUE THREAD

**Issue by genthalili** [theangryangel/logstash-output-jdbc#98]
Hi, 

Trying to use the output plugin with jdbc input.
I'm trying to transfer data from Oracle (input jdbc) to SQL server (output jdbc), but all I have is NULL values every where..

Do you know what might cause this ?
PS: Using the same fieldname for input and output.

**Comment by theangryangel** [comment]
Please post your configuration from the jdbc output section. It is impossible for me to tell you if you have a misconfiguration without it. You can remove sensitive information.

**Comment by genthalili** [comment]
Thanks for your quick reply.
Below is my config...
````
input {
                jdbc {
                                jdbc_driver_library => "C:\orarun\tnsadmin\ojdbc7.jar"
                                jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
                                jdbc_connection_string => "DB_HOST"
                                jdbc_user => "USER"
                                jdbc_password => "PASS"
                                jdbc_validate_connection => true
                                statement => "select '' AS SHPSTART,  'A' AS SHPEND, 'B' BU_CODE_CAR, 'C' as VOL_M3 , 'D' as TRSP_VOL, 'E' NUM_SHP, 'F' WEEKNO from dual"
                }
 
}
 
output{
                jdbc {
                                driver_jar_path => "C:\orarun\sqljdbc42.jar"
                                connection_string => "jdbc:sqlserver:LINK"
                                statement => [ "INSERT INTO export VALUES (?, ?, ?,?,?,?,?)", "SHPSTART", "SHPEND", "BU_CODE_CAR", "VOL_M3", "TRSP_VOL", "NUM_SHP", "WEEKNO" ]
                               
                }
}
````

In ddb I can see new lines, with all NULL, seems like field names are not matching somehow...

**Comment by theangryangel** [comment]
Looks fine.

* What version of logstash are you using and what version of the plugin?
* Have you tried adding a `stdout { codec => json }` output to the configuration just to confirm that your events have data in them when they reach the output?

**Comment by genthalili** [comment]
It version 5.6.2.

Thanks to your `stdout { codec => json }` tip I was able to see that uppercases field changed to lowercases fields. 
Changed that and now it's working :)
Thanks! 
👍
