### ISSUE TITLE
SQL server float/decimal values not saved

### ISSUE THREAD

**Issue by genthalili** [theangryangel/logstash-output-jdbc#99]
Hi, 

I'm working with SQL server and the float values are not able to be saved.
When it's a Integer, it's saved, but when it's a Float is it's inserted as a NULL value.

I also used the CAST(? as float) but not working...
my stdout is showing actually the value being a float : `"latitude" : 12.3423` but this is stored as `NULL` in the database

Any idea?

**Comment by genthalili** [comment]
Even if the field inserted as float (json stdout showing it as float), you should use the filter to convert the field.
```
filter {
  mutate {
    convert => { "fieldname" => "float" }
  }
}
```

However for `integer` and `string` conversions are working well, so you have nothing to do..

Maybe `floats` should be automatically detected and converted by the plugin ... ?

**Comment by theangryangel** [comment]
As per this line https://github.com/theangryangel/logstash-output-jdbc/blob/079c3a6c7854a30c8f24d37a8366dce6d4036577/lib/logstash/outputs/jdbc.rb#L295 it used to work 😓

I’d guess that the shipped version of jruby doesn’t send them as the float type anymore. I’ll try and find some time to investigate tomorrow, but I’m pretty busy at work and have evening plans tomorrow. Might not get time until the end of the week.

**Comment by theangryangel** [comment]
I havent been able to reproduce this problem so far... I've added support for BigDecimal in d1a733d19531ee36553e3851807c08ec8c131520. This is currently untested, but the only case I can currently think of that might be producing this problem. I'll try and get a release cut for this later this week.

If you're able to find a way to reproduce this problem, or can provide a sample event as a JSON file for me to test with, I'll happily see if there's something else going on.

**Comment by Georgeqhh** [comment]
My English is not so good,so if something I can't express well,I ask for your forgiveness.I use Logstash 5.0.2 to get mysql db data into another mysql db,when the value type is bigdecimal ,have the exception:TypeError: could not coerce BigDecimal to class java.math.BigDecimal.When I user Logstash  2.4.0,the value is null.

**Comment by Georgeqhh** [comment]
My os is windows 10

**Comment by theangryangel** [comment]
I'll take a look as soon as I can, hopefully later this afternoon.

**Comment by orgertot** [comment]
i got this too

**Comment by theangryangel** [comment]
I still need someone too give me a way to reproduce this because I can't. Until someone can give me a way, I can’t fix it.

Give me a sample config and input and I’ll look into it.

**Comment by orgertot** [comment]
`[2018-01-28T07:04:39,705][ERROR][logstash.outputs.jdbc    ] JDBC - Exception. Not retrying. event: "{"k_refnr":"1","p_geb_preis":"J","k_fk_orga_nr_3p":60300,"kzu_fk_versandart":1,"d_tr_gespreis_netto2":null,"k_fk_umst2":"A1","k_tr_brutto":0,"k_fk_vsev_nr_ap":null,"p_fk_termin_knz":null,"p_ba_wae":"EUR","k_fk_auft_abs":null,"p_sondbearb_para":null,"d_tr_ev_preis1":null,"p_msmenge_diff":0,"p_opt_weiter":null,"d_tr_preis_brutto2":null,"p_fk_numtyp_krz":"EN","p_storno":0,"p_fk_zolltarif_nr":"49019000","d_ha_preis_netto3":null,"d_ha_preis_netto1":null,"p_fk_sonder_remi_recht":null,"d_ha_preis_brutto3":null,"kzu_lbs_upbez":null,"d_ha_lp_gespreis_brutto3":null,"d_ha_gespreis_brutto1":null,"k_vor_beleg":"xxx---","k_ha_umst1_betrag":0,"d_ha_ba_gespreis_brutto2":null,"d_tr_gespreis_brutto1":null,"d_ha_preis_netto2":null,"k_nr":190000000,"kzu_best_datum":"2017-01-01T05:00:00.000Z","anlage_datum":"2017-01-01T22:13:09.000Z","kzu_abteilung":null,"p_bs_ldpreis_dm":null,"p_fk_orga_porm":null,"kzu_ls_nr":10210003,"p_rm_fl_nr":null,"d_ha_gr_gespreis_netto2":null,"p_fk_vor_beleg_art2":null,"k_umst2_proz":7,"k_belegkopiessepvs":null,"p_ha_gr_preis_netto":7.16,"kzu_ueberweisungsinfo":null,"kzu_info_para":null,"p_dep":5.65,"p_tr_gespreis_netto":0,"k_fk_aufst_ediabs":null,"d_ha_ba_gespreis_netto1":null,"p_ext_artnr_auft":"9780000000000","d_ha_gespreis_netto3":null,"kzu_vs_zahlart_p1":null,"p_ha_umst_gesbetrag":0,"k_umst1_proz":0,"d_ha_gespreis_brutto3":null,"p_ha_evpreis":10.95,"p_nr":65,"k_fk_sprache":"de","d_ha_ba_gespreis_netto3":null,"p_ha_lp_gespreis_brutto":0,"p_ha_ba_gespreis_netto":0,"d_tr_gespreis_brutto3":null,"k_fk_orga_nr_ap":60000,"p_ba_umst":"A0","p_fk_orga_lief":2849,"d_ha_gr_preis_netto1":null,"p_tr_preis_netto":6.5,"k_fk_edi_dienst":"ELS","p_lrp_nr":null,"p_besorg_kz":null,"kzu_frachtf_absender":null,"kzu_vs_zahlart_p4":null,"d_tr_preis_netto1":null,"k_fk_umst3":"A2","p_remittierbar_bis":null,"p_gewicht":268,"kzu_fk_vsdkst_schema":"BS_VTRG","netto_ek":null,"d_ha_ba_gespreis_brutto1":null,"p_wgr":null,"p_fk_artikel_nr":20700001,"k_text1":null,"p_sondbearb_nr":null,"p_art_umst":"A1","d_ha_umst1_gesbetrag":null,"p_auspr2":null,"p_fk_ms_nr":99,"wgr_krz":"14450","k_ha_brutto":0,"p_tr_evpreis":10.95,"p_remibezugsdaten":null,"p_fk_leistungsart":null,"d_fk_ask_id":null,"d_ha_gespreis_brutto2":null,"k_beleglayout":1034,"k_fk_vsev_nr_3p":null,"k_bestellzeichen":"42000000","kzu_fk_tour_nr":849,"kzu_fk_tourschema":"S009","p_azp_erg2":null,"k_tr_netto":0,"k_fk_tr_wae":"EUR","p_fk_rjsort_nr":null,"k_ustlief_kenz":"INL","p_fk_tr_wae":"EUR","d_tr_gespreis_netto1":null,"d_ha_lp_gespreis_netto1":null,"k_fk_ha_wae":"EUR","k_fk_edi_format":"EAN","k_fk_vsev_nr_vp":null,"kzu_pfkt_nr":null,"update_datum":null,"k_umst3_proz":19,"d_tr_preis_brutto3":null,"p_int_artnr_auft":20700001,"p_aw1":"EUR","d_tr_ev_preis2":null,"k_fk_orga_nr_abs":8,"p_fk_qualnr":0,"p_fk_rjabt_nr":null,"p_chargeliefinfo":null,"k_ha_netto1":0,"k_fk_beleg_art":"BSLS","p_ls_gel_mng":0,"p_azp_erg1":"A02","kzu_multitext":null,"d_ha_preis_brutto2":null,"p_fk_chargennr":null,"p_ha_preis_netto":0,"p_ha_gr_gespreis_netto":0,"k_belegkopies":0,"k_fk_adr_nr_abs":200009,"k_gewicht_brutto":0,"kzu_uin_ap":null,"kzu_lrk_nr":null,"k_fk_bk_nr":1,"p_ba_preis":5.65,"k_ha_wa_wert_netto":0,"kzu_ff_sortinfo":null,"k_ap_plz":null,"p_ha_gespreis_netto":0,"kzu_paketidentcode":null,"kzu_versandlabel_layout":null,"p_fk_bonus":23,"k_tr_umst1_betrag":0,"k_tr_wa_wert":0,"k_tr_netto3":0,"p_vor_beleg":"316000000-00100-000-001","k_n_steu":0,"d_ha_gr_gespreis_netto3":null,"p_refnr":"1","p_ls_best_mng":1,"k_fk_adr_nr_ap":600000,"p_aw2":null,"p_ppf_erg":"F33","k_tr_umst3_betrag":0,"p_vorgemerkt":"N","k_gewicht":0,"d_ha_gr_preis_netto2":null,"d_ha_gr_preis_netto3":null,"d_tr_gespreis_netto3":null,"k_tr_wa_wert_netto":0,"d_tr_preis_brutto1":null,"k_ha_netto3":0,"p_liefer_termin":null,"p_fk_umst":"A1","k_fk_vor_beleg_art":"AUFT","kzu_fk_zbed_nr":158,"d_tr_gespreis_brutto2":null,"d_ha_lp_gespreis_netto2":null,"p_pos_text":null,"k_ha_umst2_betrag":0,"k_beleg_nr":10210000,"kzu_verpackungsart":1,"k_tr_netto1":0,"p_fk_msaddon_nr":null,"update_user":null,"k_tr_netto2":0,"kzu_vs_zahlart_p3":null,"p_fk_vor_beleg_art":"AUFT","d_ha_gespreis_netto1":null,"p_lager_sondbearb_para":null,"kzu_te_nr":"0","k_fk_umst1":"A0","p_fk_orga_herst":2800,"k_ha_netto2":0,"p_bestellzeichen":"42Q00000","p_ms_menge":1,"p_ha_ba_gespreis_brutto":0,"p_art_nr":"9783700000000","k_fk_adr_nr_3p":600000,"d_ha_umst3_gesbetrag":null,"d_ha_lp_gespreis_netto3":null,"@version":"1","@timestamp":"2018-01-28T12:04:39.476Z","p_rj_sort_aktion":null,"d_tr_umst3_gesbetrag":null,"k_ap_adr":null,"p_vor_beleg2":null,"k_fk_edi_weg":"ASSEND","anlage_user":"ORA_LS_INSERT","p_umst_proz":7,"kzu_bypasslabel":null,"kzu_fk_vszart_nr":0,"kzu_lbs_tour":null,"p_fk_orga_abs":null,"p_lager_sondbearb_nr":null,"d_tr_preis_netto2":null,"d_tr_preis_netto3":null,"kzu_ueberweisungslayout":null,"k_ha_umst3_betrag":0,"p_tr_gespreis_brutto":0,"kzu_ls_barcode":"4026635820170100010000","p_ha_ba_preis":5.65,"k_ha_netto":0,"p_ha_lp_gespreis_netto":0,"p_remigrund":null,"d_ha_gr_gespreis_netto1":null,"d_ha_ba_gespreis_netto2":null,"d_ha_gespreis_netto2":null,"d_tr_ev_preis3":null,"p_fk_auft_ugbesorg":null,"p_tr_preis_brutto":6.96,"k_refnr2":null,"p_bs_vk_rabatt":36.44,"k_fk_wrk_krz":"BH","k_fk_edi_aufst_nr":"S1","kzu_vs_zahlart_p2":null,"p_auspr1":10.95,"k_fk_lager_ort_krz":"01","p_remittierbar_bis_typ":null,"p_vk_grundrabatt":30,"d_ha_lp_gespreis_brutto1":null,"kzu_remigennr":null,"p_melde_mng":0,"k_fk_orga_mdt":1,"p_ha_preis_brutto":0,"p_fk_buchschl_nr":100,"d_ha_preis_brutto1":null,"k_beleglayoutsepvs":null,"d_ha_lp_gespreis_brutto2":null,"k_tr_umst2_betrag":0,"kzu_bonus":null,"k_beleg_datum":"2017-01-01T05:00:00.000Z","k_fk_adr_nr_label":null,"kzu_fk_frachtf":"BXP","k_fk_adr_nr_vp":225000,"p_lieferhinweis":null,"k_fk_aufst_nr":"A1","k_fk_orga_nr_vp":1,"kzu_leitcode":null,"k_text2":null,"p_numtyp_auft":"EN","k_fk_orga_nr_label":null,"k_ha_wa_wert":0,"p_ha_gespreis_brutto":0,"d_ha_ba_gespreis_brutto3":null,"p_frei_ex":0,"k_beleglogo":2001,"p_ba_prtyp_krz":null,"k_ap_land_iso":null,"p_tr_umst_gesbetrag":0,"d_tr_umst1_gesbetrag":null,"sem_nr":null,"d_tr_umst2_gesbetrag":null,"d_ha_umst2_gesbetrag":null}". {:exception=>#<TypeError: could not coerce BigDecimal to class java.math.BigDecimal>}
`
and a jdbc input and jdbc output..

**Comment by theangryangel** [comment]
What version of the plugin and logstash are you using? I thought the fix for the BigDecimal conversion was released a while ago...

**Comment by orgertot** [comment]
the most recent one.. I did a fresh installation

**Comment by Georgeqhh** [comment]
jdbc: "typ"=>"user", "balance"=>#<BigDecimal:901fe3,'0.802E1',3(4)>, "@version"=>"1"
stdout:
{
             "id" => 3,
           "name" => "3",
    "create_time" => "2018-02-26T10:16:27.000Z",
    "update_time" => "2018-02-26T15:49:05.000Z",
            "typ" => "user",
        "balance" => 8.02,
       "@version" => "1",
     "@timestamp" => "2018-02-27T06:23:50.278Z",
           "type" => "user",
            "key" => "value"
}
Then,"balance" in mysql is null.

**Comment by karnamonkster** [comment]
+1
